camera:
  - platform: generic
    name: Radar
    still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BUF&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25396520

  - platform: generic
    name: Living Room
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_living_pic_url
    # stream_source: !secret cam_living_url

  - platform: generic
    name: Weston's Room
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_weston_pic_url
    # stream_source: !secret cam_weston_url
    
  - platform: generic
    name: Harrison's Room
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_harrison_pic_url
    # stream_source: !secret cam_harrison_url

  - platform: generic
    name: Garage
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_garage_pic_url
    # stream_source: !secret cam_garage_url

  - platform: generic
    name: Driveway
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_driveway_pic_url
    # stream_source: !secret cam_driveway_url

  - platform: generic
    name: Front Door
    username: !secret amcrest_user
    password: !secret amcrest_pass
    still_image_url: !secret cam_front_door_pic_url
    stream_source: !secret cam_front_door_url

  - platform: generic
    name: Backyard
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_backyard_pic_url
    # stream_source: !secret cam_backyard_url
