camera:
  - platform: generic
    name: Radar
    still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BUF&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25396520

# Zone Minder Cameras
  - platform: mjpeg
    name: Living Room
    still_image_url: !secret cam_zm_living_pic_url
    mjpeg_url: !secret cam_zm_living_url

  - platform: mjpeg
    name: Weston's Room
    still_image_url: !secret cam_zm_weston_pic_url
    mjpeg_url: !secret cam_zm_weston_url
    
  - platform: mjpeg
    name: Harrison's Room
    still_image_url: !secret cam_zm_harrison_pic_url
    mjpeg_url: !secret cam_zm_harrison_url

  - platform: mjpeg
    name: Garage
    still_image_url: !secret cam_zm_garage_pic_url
    mjpeg_url: !secret cam_zm_garage_url

  - platform: mjpeg
    name: Driveway
    still_image_url: !secret cam_zm_driveway_pic_url
    mjpeg_url: !secret cam_zm_driveway_url

  - platform: mjpeg
    name: Front Door
    still_image_url: !secret cam_zm_front_door_pic_url
    mjpeg_url: !secret cam_zm_front_door_url

  - platform: mjpeg
    name: Backyard
    still_image_url: !secret cam_zm_backyard_pic_url
    mjpeg_url: !secret cam_zm_backyard_url

# Direct Cameras, for casting
  - platform: generic
    name: Weston's Room Stream
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_weston_pic_url
    stream_source: !secret cam_weston_url
  
  - platform: generic
    name: Harrison's Room Stream
    verify_ssl: false
    username: !secret cam_user
    password: !secret cam_pass
    still_image_url: !secret cam_harrison_pic_url
    stream_source: !secret cam_harrison_url