camera:
  - platform: generic
    name: Radar
    still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BUF&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25396520

# Direct Cameras
  # - platform: mjpeg
  #   name: Garage
  #   mjpeg_url: !secret cam_garage_url
  #   still_image_url: !secret cam_garage_pic_url

  # - platform: generic
  #   name: Weston's Room
  #   verify_ssl: false
  #   username: !secret cam_user
  #   password: !secret cam_pass
  #   framerate: 5
  #   still_image_url: !secret cam_weston_pic_url
  #   stream_source: !secret cam_weston_url
    
  # - platform: generic
  #   name: Harrison's Room
  #   verify_ssl: false
  #   username: !secret cam_user
  #   password: !secret cam_pass
  #   framerate: 5
  #   still_image_url: !secret cam_harrison_pic_url
  #   stream_source: !secret cam_harrison_url

  # - platform: generic
  #   name: Living Room
  #   verify_ssl: false
  #   username: !secret cam_user
  #   password: !secret cam_pass
  #   framerate: 5
  #   still_image_url: !secret cam_living_pic_url
  #   stream_source: !secret cam_living_url

  # - platform: generic
  #   name: Driveway
  #   verify_ssl: false
  #   username: !secret cam_user
  #   password: !secret cam_pass
  #   framerate: 5
  #   still_image_url: !secret cam_driveway_pic_url
  #   stream_source: !secret cam_driveway_url

# Motion Eye Cameras
  - platform: mjpeg
    name: Garage
    mjpeg_url: !secret cam_mo_garage_url
    still_image_url: !secret cam_mo_garage_pic_url

  - platform: mjpeg
    name: Weston's Room
    still_image_url: !secret cam_mo_weston_pic_url
    mjpeg_url: !secret cam_mo_weston_url
    
  - platform: mjpeg
    name: Harrison's Room
    still_image_url: !secret cam_mo_harrison_pic_url
    mjpeg_url: !secret cam_mo_harrison_url

  - platform: mjpeg
    name: Living Room
    still_image_url: !secret cam_mo_living_pic_url
    mjpeg_url: !secret cam_mo_living_url

  - platform: mjpeg
    name: Driveway
    still_image_url: !secret cam_mo_driveway_pic_url
    mjpeg_url: !secret cam_mo_driveway_url

  - platform: mjpeg
    name: Front Door
    still_image_url: !secret cam_mo_front_door_pic_url
    mjpeg_url: !secret cam_mo_front_door_url

# Shinobi Cameras
  # - platform: mjpeg
  #   name: Garage
  #   mjpeg_url: !secret cam_sh_garage_url
  #   still_image_url: !secret cam_sh_garage_pic_url

  # - platform: generic
  #   name: Weston's Room
  #   still_image_url: !secret cam_sh_weston_pic_url
  #   stream_source: !secret cam_sh_weston_url
    
  # - platform: generic
  #   name: Harrison's Room
  #   still_image_url: !secret cam_sh_harrison_pic_url
  #   stream_source: !secret cam_sh_harrison_url

  # - platform: generic
  #   name: Living Room
  #   still_image_url: !secret cam_sh_living_pic_url
  #   stream_source: !secret cam_sh_living_url

  # - platform: generic
  #   name: Driveway
  #   still_image_url: !secret cam_sh_driveway_pic_url
  #   stream_source: !secret cam_sh_driveway_url

# Direct Cameras, for casting
  - platform: generic
    name: Weston's Room Stream
    verify_ssl: false
    still_image_url: !secret cam_weston_pic_url
    stream_source: !secret cam_weston_url
  
  - platform: generic
    name: Harrison's Room Stream
    verify_ssl: false
    still_image_url: !secret cam_harrison_pic_url
    stream_source: !secret cam_harrison_url