camera:
  - platform: skybell
    monitored_conditions:
      - avatar
      - activity
    activity_name: "Last Activity"

  - platform: generic
    name: Radar
    still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BUF&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25396520

  - platform: mjpeg
    name: Garage
    mjpeg_url: !secret cam_garage_url
    still_image_url: !secret cam_garage_pic_url

  - platform: generic
    name: Weston's Room
    still_image_url: !secret cam_westons_pic_url
    stream_source: !secret cam_westons_url
    verify_ssl: false
    username: !secret cam_user
    password:  !secret cam_pass
    authentication: basic
    
  - platform: generic
    name: Harrison's Room
    still_image_url: !secret cam_harrisons_pic_url
    stream_source: !secret cam_harrisons_url
    verify_ssl: false
    username: !secret cam_user
    password:  !secret cam_pass
    authentication: basic

  - platform: generic
    name: Living Room
    still_image_url: !secret cam_living_pic_url
    stream_source: !secret cam_living_url
    verify_ssl: false
    username: !secret cam_user
    password:  !secret cam_pass
    authentication: basic

  - platform: generic
    name: Driveway
    still_image_url: !secret cam_driveway_pic_url
    stream_source: !secret cam_driveway_url
    verify_ssl: false
    username: !secret cam_user
    password:  !secret cam_pass
    authentication: basic
