cast:
  media_player:
    - host: !secret ghome_living_ip
    - host: !secret gmini_master_ip
    - host: !secret gmini_weston_ip
    - host: !secret gmini_harrison_ip
    - host: !secret gnest_hub_ip
