google_assistant: 
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  secure_devices_pin: !secret google_assistant_pin
  exposed_domains:
    - switch
    - light
    - cover
    - fan
    - scene
    - script
    - input_boolean
    # - media_player
    # - group
    # - climate
  entity_config:
################### Kitchen #############################
    light.kitchen_up:
      room: Kitchen
      name: Kitchen Down Lights
    light.kitchen_down:
      room: Kitchen
      name: Kitchen Up Lights
################## Living Room ##########################
    switch.living_room_outlet:
      room: Living Room
      name: Living Room Outlet
      aliases:
        - Living Room Outlet
        - Christmas Tree
################## Office ################################
    switch.office_outlet:
      room: Office
      name: Office Outlet
################## Outside ###############################
    switch.driveway_light:
      room: Outside
      name: Driveway Light
    switch.porch_light:
      room: Outside
      name: Porch Light
    light.front_door:
      room: Outside
      name: Doorbell Light
    cover.garage_door_opener:
      room: Outside
      name: Garage Door
################## Weston's Room #########################
    input_boolean.weston_nap:
      room: Weston's Room
    fan.weston_fan:
      room: Weston's Room
################## Harrison's Room #######################
    input_boolean.harrison_nap:
      room: Harrison's Room
################## Disabled ##############################
    switch.skybell_front_door_motion_sensor:
      expose: false
    sensor.custom_python_script_tracker:
      expose: false
