google_assistant: 
  project_id: !secret google_assistant_project_id
  # api_key: !secret google_assistant_api_key
  service_account: !include ../google-service-account.json
  secure_devices_pin: !secret google_assistant_pin
  report_state: true
  exposed_domains:
    - camera
    # - group
    - input_boolean
    - scene
    - script
    - switch
    - fan
    - light
    - lock
    - cover
    # - media_player
    # - climate
    - vacuum
    - sensor
  entity_config:
################### Kitchen #############################
    light.kitchen_up:
      room: Kitchen
      name: Kitchen Down Lights
    light.kitchen_down:
      room: Kitchen
      name: Kitchen Up Lights
################## Living Room ##########################
    switch.living_room_corner:
      room: Living Room
      name: Living Room Outlet
      aliases:
        - Living Room Outlet Corner
        - Christmas Tree
    switch.living_room_stairs:
      room: Living Room
      name: Living Room Outlet Stairs
    input_boolean.guest_mode:
      room: Living Room
    vacuum.deebot:
      room: Living Room
################## Office ################################
    switch.office_outlet:
      room: Office
      name: Office Outlet
    switch.gaming_pc:
      room: Office
    light.office_lamp:
      name: Office Lamp
      room: Office
################## Outside ###############################
    switch.driveway_light:
      room: Outside
      name: Driveway Light
    switch.porch_light:
      room: Outside
      name: Porch Light
    light.garage_leds:
      room: Outside
      name: Garage LEDs
    light.porch_leds:
      room: Outside
      name: Porch LEDs
    light.front_door:
      room: Outside
      name: Doorbell Light
    cover.garage_door_opener:
      room: Outside
      name: Garage Door
################## Weston's Room #########################
    input_boolean.weston_nap:
      room: Weston's Room
    fan.weston_fan:
      room: Weston's Room
    light.weston_lamp:
      room: Weston's Room
################## Harrison's Room #######################
    input_boolean.harrison_nap:
      room: Harrison's Room
    fan.harrison_fan:
      room: Harrison's Room
################## Masters's Room ########################
    fan.master_fan:
      room: Master Bedroom
################## Whole House ###########################
    script.goodmorning:
      name: Goodmorning
    script.goodnight:
      name: Goodnight

################## Excluded ##############################
    media_player.westons_room_speaker:
      expose: false
    media_player.harrisons_room_speaker:
      expose: false
    media_player.master_bedroom_speaker:
      expose: false
    media_player.kitchen_display:
      expose: false
    media_player.office_speaker:
      expose: false
    sensor.family_room_thermostat_target:
      expose: false
    sensor.family_room_thermostat_temperature:
      expose: false
    sensor.family_room_thermostat_humidity:
      expose: false
