input_boolean:
  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup
  weston_nap:
    name: Weston Nap
    icon: mdi:alpha-w
  harrison_nap:
    name: Harrison Nap
    icon: mdi:alpha-h
  justin_sleeping:
    name: Justin Sleeping
    icon: mdi:alpha-j
  shannon_sleeping:
    name: Shannon Sleeping
    icon: mdi:alpha-s
