# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.bolt_location_update
    entity_globs:
      - binary_sensor.pixel_4a_*
      - sensor.pixel_4a_*
      - binary_sensor.pixel_3a_xl_*
      - sensor.pixel_3a_xl_*
