# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.bolt_location_update
      - sensor.spa_last_ping
    entity_globs:
      - binary_sensor.pixel_4a_*
      - sensor.pixel_4a_*
      - binary_sensor.pixel_5a_*
      - sensor.pixel_5a_*
      - binary_sensor.jbassett_*
      - sensor.jbassett_*
