lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/power-wheel-card/power-wheel-card.js
    - type: module
      url: /hacsfiles/pc-card/pc-card.js
    - type: module
      url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - type: module
      url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    - type: module
      url: /hacsfiles/weather-card/weather-card.js
    - type: module
      url: /hacsfiles/roku-card/roku-card.js
    - type: module
      url: /hacsfiles/atomic_calendar/atomic_calendar.js
    - type: module
      url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    - type: module
      url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    - type: module
      url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
    - type: js
      url: /hacsfiles/button-entity-row/button-entity-row.js
    - type: js
      url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
    - type: js
      url: /hacsfiles/lovelace-card-tools/card-tools.js
    - type: js
      url: /hacsfiles/lovelace-more-info-card/more-info-card.js
    - type: js
      url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    - type: js
      url: /hacsfiles/lovelace-layout-card/layout-card.js
    - type: js
      url: /hacsfiles/simple-thermostat/simple-thermostat.js
