utility_meter:
  house_daily_net_energy:
    source: sensor.solar_raw_lifetime_net_energy
    cycle: daily
    net_consumption: True
  house_monthly_net_energy:
    source: sensor.solar_raw_lifetime_net_energy
    cycle: monthly
    net_consumption: True
  solar_daily_energy:
    source: sensor.solar_raw_lifetime_panel_energy
    cycle: daily
  solar_monthly_energy:
    source: sensor.solar_raw_lifetime_panel_energy
    cycle: monthly
