
DOMAIN = "bryx911"

TYPE_KEEP_ALIVE = 9
TYPE_UPDATE_PUSH = 5
TYPE_ACK = 6
TYPE_INITAL_JOBS = 1
TYPE_JOB_UNSUB = 2
TYPE_JOB_SUB = 0

CONF_API_KEY = 'api_key'
CONF_USER = 'username'
CONF_PASS = 'password'
CONF_DEVICE_ID = 'device_id'
