- action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_on
  alias: Turn on lights in evening
  condition: []
  id: '1523965566198'
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
- action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_off
  alias: Turn off lights in morning
  condition: []
  id: '1523965652845'
  trigger:
  - event: sunrise
    offset: 00:15:00
    platform: sun
- action:
  - data:
      data:
        actions:
        - action: close_garage
          title: Close Door
      message: Looks like the garage was left open!! {{ now().strftime("%H:%M") }}
      title: Garage left open!
    service: notify.web
  alias: '[Notification] Garage Left Open'
  condition:
  - condition: state
    entity_id: cover.garage_door_opener
    state: open
  id: '1523975149744'
  trigger:
  - entity_id: device_tracker.justin_pixel
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.shannon_motox4
    from: home
    platform: state
    to: not_home
- action:
  - data:
      entity_id: cover.garage_door_opener
    service: cover.close_cover
  alias: '[Notification - Action] Close Garage'
  condition: []
  id: '1523975760898'
  trigger:
  - event_data:
      action: close_garage
    event_type: html5_notification.clicked
    platform: event
- id: '1524146043949'
  alias: '[Notification] Open Garage'
  trigger:
  - above: '0'
    below: '2'
    entity_id: proximity.home_justin
    platform: numeric_state
  condition:
  - condition: state
    entity_id: cover.garage_door_opener
    state: closed
  - condition: template
    value_template: '{{ states.proximity.home_justin.attributes.dir_of_travel == "towards"
      }}'
  action:
  - data:
      data:
        actions:
        - action: open_garage
          title: Open Door
      message: Would you like to open the garage door?
      title: Almost Home!
    service: notify.web
- action:
  - data:
      entity_id: cover.garage_door_opener
    service: cover.open_cover
  alias: '[Notification - Action] Open Garage'
  condition: []
  id: '1524146180812'
  trigger:
  - event_data:
      action: open_garage
    event_type: html5_notification.clicked
    platform: event
- id: '1524579938313'
  alias: '[Notification] Garage Opened/Closed'
  trigger:
  - entity_id: cover.garage_door_opener
    from: open
    platform: state
    to: closed
  - entity_id: cover.garage_door_opener
    from: closed
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  action:
  - data:
      data:
        actions:
        - action: close_garage
          title: Close Door
        - action: open_garage
          title: Open Door
      message: Garage is now {{ states('cover.garage_door_opener') }} at {{ now().strftime("%H:%M")
        }}
      title: 'Garage Door: {{ states(''cover.garage_door_opener'') }}'
    service: notify.web
- id: '1525229495345'
  alias: '[TTS] Door Motion'
  trigger:
  - entity_id: binary_sensor.skybell_front_door_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data:
      message: Someone is at the front door.
    entity_id: media_player.living_room_speaker
    service: tts.google_say
- id: '1529578174545'
  alias: '[TTS] Shannon Almost Home'
  trigger:
  - above: '0'
    below: '2'
    entity_id: proximity.home_shannon
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ states.proximity.home_shannon.attributes.dir_of_travel ==
      "towards" }}'
  action:
  - data:
      message: Shannon is almost home!
    service: tts.google_say
- id: '1529578278693'
  alias: '[TTS] Justin Almost Home'
  trigger:
  - above: '0'
    below: '2'
    entity_id: proximity.home_justin
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ states.proximity.home_justin.attributes.dir_of_travel == "towards"
      }}'
  action:
  - data:
      message: Justin in almost home!
    service: tts.google_say
