#- platform: ffmpeg
#  name: Front Yard
#  input: !secret camera_front_input

- platform: skybell
  monitored_conditions:
    - avatar
    - activity
  activity_name: "Last Activity"

- platform: generic
  name: Radar
  still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BUF&brand=wui&num=6&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25396520

- platform: mjpeg
  name: Garage
  mjpeg_url: !secret garage_cam_video
  still_image_url: !secret garage_cam_still

- platform: generic
  name: Weston's Room
  still_image_url: !secret westons_cam_still
  # mjpeg_url: !secret westons_cam_video
  stream_source: !secret westons_cam_video
  verify_ssl: false
  username: !secret westons_cam_user
  password:  !secret westons_cam_pass
  authentication: basic
  
- platform: generic
  name: Harrison's Room
  still_image_url: !secret harrisons_cam_still
  # mjpeg_url: !secret harrisons_cam_video
  stream_source: !secret harrisons_cam_video
  verify_ssl: false
  username: !secret harrisons_cam_user
  password:  !secret harrisons_cam_pass
  authentication: basic

- platform: generic
  name: Living Room
  still_image_url: !secret living_cam_still
  # mjpeg_url: !secret living_cam_video
  stream_source: !secret living_cam_video
  verify_ssl: false
  username: !secret living_cam_user
  password:  !secret living_cam_pass
  authentication: basic

- platform: generic
  name: Driveway
  still_image_url: !secret driveway_cam_still
  stream_source: !secret driveway_cam_video
  verify_ssl: false
  username: !secret driveway_cam_user
  password:  !secret driveway_cam_pass
  authentication: basic
