homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat_num
  longitude: !secret home_lon_num
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_num
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

  auth_providers:
   - type: homeassistant

# Enable the auth component
auth:

# Enables the frontend
frontend:
  javascript_version: auto
  themes: !include_dir_merge_named themes/

person:
  - id: jbassett
    name: Justin
    user_id: 5a10d3ad221d4dc384ea626243287ba5
    device_trackers:
      - device_tracker.google_maps_114722593006578537688
      - device_tracker.justin_pixel
  - id: sbassett
    name: Shannon
    user_id: 7b2802e34eba4b19b628c0cf6874e4e6
    device_trackers:
      - device_tracker.google_maps_112779943779309085408
      - device_tracker.shannon_motox4

lovelace:
  mode: yaml

http: !include http.yaml

browser_mod:
  prefix: "browser_"

hacs:
  token: !secret github_pat
  python_script: True
  theme: True
  # options:
  #   experimental: True

python_script:

# Enables the config panels
config:

system_health:

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_keep_days: 30
  purge_interval: 2
  db_url: !secret mariadb_url

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

influxdb:
  host: !secret influx_ip
  database: homeassistant
  username: !secret influx_user
  password: !secret influx_pass
  include:
    domains:
      - sensor

logger:
  default: warn
  logs:
    sucks: error

# Track the sun
sun:

stream:

# Text to speech
tts:
  platform: google_translate

zone: !include zone.yaml
proximity: !include proximity.yaml

wake_on_lan:

google_assistant: !include google_assistant.yaml

notify:
  - name: web
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

mychevy:
  username: !secret mychevy_user
  password: !secret mychevy_pass

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

skybell:
  username: !secret skybell_user
  password: !secret skybell_pass

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

sabnzbd:
  host: !secret sabnzbd_ip
  port: !secret sabnzbd_port
  api_key: !secret sabnzbd_api
  sensors:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'
    - 'queue_count'

utility_meter:
  house_daily_net_energy:
    source: sensor.solar_raw_lifetime_net_energy
    cycle: daily
    net_consumption: True
  house_monthly_net_energy:
    source: sensor.solar_raw_lifetime_net_energy
    cycle: monthly
    net_consumption: True
  solar_daily_energy:
    source: sensor.solar_raw_lifetime_panel_energy
    cycle: daily
  solar_monthly_energy:
    source: sensor.solar_raw_lifetime_panel_energy
    cycle: monthly

speedtestdotnet:
  scan_interval:
    hours: 1

ecovacs:
  username: !secret ecovacs_user
  password: !secret ecovacs_pass
  country: US
  continent: NA

plex:
  host: !secret plex_ip
  token: !secret plex_token

plex_webhooks:
  webhook_id: !secret plex_webhook_id

cast:
  media_player:
    - host: !secret ghome_living_ip
    - host: !secret gmini_master_ip
    - host: !secret gmini_weston_ip
    - host: !secret gmini_harrison_ip

roku:
  - host: !secret tv_living_room_ip

input_boolean:
  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup
  weston_nap:
    name: Weston Nap
    icon: mdi:alpha-w
  harrison_nap:
    name: Harrison Nap
    icon: mdi:alpha-h
  dark_outside:
    name: Dark Outside
    icon: mdi:weather-night

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
cover: !include cover.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include_dir_merge_list sensors
switch: !include switch.yaml
media_player: !include media_player.yaml
device_tracker: !include device_tracker.yaml
camera: !include camera.yaml
light: !include light.yaml
group: !include group.yaml
shell_command: !include shell_command.yaml
script: !include_dir_merge_named scripts
rest_command: !include_dir_merge_named rest_commands
