homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml

  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
        - 192.168.1.0/24

# Enable the auth component
auth:

# Enables the frontend
frontend:
  javascript_version: auto
  themes: !include themes.yaml

person:
  - id: jbassett
    name: Justin
    user_id: 5a10d3ad221d4dc384ea626243287ba5
    device_trackers:
      - device_tracker.google_maps_114722593006578537688
      - device_tracker.justin_pixel
  - id: sbassett
    name: Shannon
    user_id: 7b2802e34eba4b19b628c0cf6874e4e6
    device_trackers:
      - device_tracker.google_maps_112779943779309085408
      - device_tracker.shannon_motox4

lovelace:
  mode: yaml

http: !include http.yaml

custom_updater:
  show_installable: true
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/gurbyz/custom-cards-lovelace/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

map:

# Enables the config panels
config:

system_health:

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_user
#   password: !secret mqtt_pass
#   discovery: true
#   discovery_prefix: homeassistant

recorder:
  purge_keep_days: 14
  purge_interval: 2
  db_url: !secret mariadb_url

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

logger:
  default: warn
  logs:
    # homeassistant.components.stream: debug
    custom_components.sensor.sunpower: debug

# Track the sun
sun:

# stream:

# Text to speech
tts:
  platform: google_translate

zone: !include zone.yaml
proximity: !include proximity.yaml

wake_on_lan:

google_assistant: !include google_assistant.yaml

notify:
  - name: web
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

zwave:
  usb_path: /zwaveusbstick
  config_path: /config/openzwave/
  device_config: !include zwave_device_config.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

skybell:
  username: !secret skybell_user
  password: !secret skybell_pass

august:
  login_method: email
  username: !secret august_user
  password: !secret august_pass

weather:
  - platform: darksky
    api_key: !secret darksky_key

sabnzbd:
  host: !secret sabnzbd_host
  port: !secret sabnzbd_port
  api_key: !secret sabnzbd_api
  sensors:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'
    - 'queue_count'

utility_meter:
  house_daily_net_energy:
    source: sensor.solar_raw_lifetime_net_energy
    cycle: daily
    net_consumption: True
  house_monthly_net_energy:
    source: sensor.solar_raw_lifetime_net_energy
    cycle: monthly
    net_consumption: True
  solar_daily_energy:
    source: sensor.solar_raw_lifetime_panel_energy
    cycle: daily
  solar_monthly_energy:
    source: sensor.solar_raw_lifetime_panel_energy
    cycle: monthly

speedtestdotnet:
  scan_interval:
    hours: 1

ecovacs:
  username: !secret ecovacs_user
  password: !secret ecovacs_pass
  country: US
  continent: NA

cast:
  media_player:
    - host: !secret google_home_host
    - host: !secret master_bedroom_tv_host
    - host: !secret westons_room_host

input_boolean:
  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup

automation: !include automations.yaml
automation old: !include_dir_merge_list automations
cover: !include cover.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include_dir_merge_list sensors
switch: !include switch.yaml
media_player: !include media_player.yaml
device_tracker: !include device_tracker.yaml
camera: !include camera.yaml
light: !include light.yaml
group: !include group.yaml
shell_command: !include shell_command.yaml
script: !include script.yaml

# Custom Component
# sunpower:
#   username: demo@sunpower.com
#   password: sun
