- platform: snmp
  track_new_devices: false
  host: !secret pfsense_host
  community: public
  baseoid: 1.3.6.1.2.1.4.22.1.2

- platform: google_maps
  username: !secret maps_user
  password: !secret maps_pass
