- platform: lg_netcast
  host: !secret master_bedroom_tv_host
  access_token: !secret master_bedroom_tv_access_token

- platform: xboxone
  ip_address: !secret xbox_ip
  device: !secret xbox_device_id
  name: Living Room Xbox One
