- platform: plex

- platform: cast

- platform: cast
  host: !secret google_home_host

- platform: cast
  host: !secret master_bedroom_tv_host

- platform: lg_netcast
  host: !secret living_room_tv_host
  access_token: !secret living_room_tv_access_token
