- platform: lg_netcast
  host: !secret living_room_tv_host
  access_token: !secret living_room_tv_access_token

- platform: xboxone
  ip_address: !secret xbox_ip
  device: !secret xbox_device_id
  name: Living Room Xbox One
