resources:
  - url: /local/lovelace/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: /local/lovelace/tracker-card/tracker-card.js?v=0.1.4
    type: js
  - url: /local/lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.9
    type: js

title: Misty Way
views:
  - title: Home
    tab_icon: mdi:home
    cards:
      - type: entities
        title: Locations
        entities:
          - device_tracker.google_maps_114722593006578537688
          - device_tracker.google_maps_112779943779309085408
      - type: picture-glance
        title: Front Door
        camera_image: camera.front_door
        entities:
          - light.front_door
      - type: entities
        title: Garage
        entities:
          - cover.garage_door_opener
      - type: entities
        title: Thermostat
        entities:
          - climate.family_room
          - binary_sensor.family_room_thermostat_has_leaf
          - sensor.family_room_thermostat_temperature
          - sensor.family_room_thermostat_target
          - sensor.family_room_thermostat_humidity
      - type: history-graph
        title: Thermostat History
        hours_to_show: 6
        refresh_interval: 60
        entities:
          - sensor.family_room_thermostat_temperature
          - sensor.dark_sky_temperature
          - sensor.family_room_thermostat_target
          - sensor.family_room_thermostat_hvac_state
          - binary_sensor.family_room_thermostat_fan
      - type: entities
        title: Outdoor Lights
        entities:
          - switch.porch_light
          - switch.driveway_light
          - light.front_door
      - type: entities
        title: Ride Sharing to ROC
        entities:
          - sensor.lyft_time
          - sensor.lyft_price
          - sensor.lyft_xl_time
          - sensor.lyft_xl_price
          - sensor.uberx_time
          - sensor.uberx_price
          - sensor.uberxl_time
          - sensor.uberxl_price

  - title: Solar
    cards:
      - type: glance
        title: Current Power Stats
        entities:
          - sensor.solar_raw_total_power
          - sensor.solar_raw_lifetime_net_energy
          - sensor.solar_raw_house_usage
          - sensor.solar_raw_export
      - type: entities
        title: Current Energy Stats
        entities:
          - sensor.yesterdays_net_energy_consumption
          - sensor.todays_net_energy_consumption
      - type: history-graph
        title: Overall Usage
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.solar_raw_total_power
          - sensor.solar_raw_house_usage
          - sensor.solar_raw_export
      - type: history-graph
        title: Overall Usage Smoothed
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.current_solar_power
          - sensor.current_house_usage
          - sensor.current_power_export
      - type: custom:monster-card
        card:
          type: history-graph
          title: Individual Panels
          hours_to_show: 24
          refresh_interval: 60
        filter:
          include:
            - entity_id: "sensor.solar_inverter*"

  - title: First Floor
    cards:
      - type: media-control
        entity: media_player.plex_xboxone
      - type: media-control
        entity: media_player.lg_tv_remote
      - type: media-control
        entity: media_player.living_room_speaker
      - type: entities
        title: Office
        entities:
          - switch.office_outlet

  - title: Second Floor
    cards:
      - type: media-control
        entity: media_player.master_bedroom_tv

  - title: Media
    cards:
      - type: entities
        title: Xbox
        entities:
          - script.turn_on_xbox
      - type: media-control
        entity: media_player.lg_tv_remote
      - type: media-control
        entity: media_player.plex_xboxone
      - type: entities
        title: Plex
        entities:
          - sensor.plex
      - type: entities
        title: Movies
        entities:
          - sensor.radarr_upcoming
          - sensor.radarr_movies
          - sensor.radarr_status
      - type: entities
        title: TV Shows
        entities:
          - sensor.sonarr_upcoming
          - sensor.sonarr_wanted
      - type: custom:upcoming-media-card
        service: sonarr
        title: Upcoming TV Shows
        image_style: banner
        clock: 24
      - type: custom:upcoming-media-card
        service: radarr
        title: Upcoming Movies
        #image_style: banner
        clock: 24

  - title: Weather
    tab_icon: mdi:weather-cloudy
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: picture-entity
        title: Radar
        entity: camera.radar
        show_info: false

  - title: Settings
    tab_icon: mdi:harddisk
    cards:
      - type: entities
        title: Speedtest
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
      - type: entities
        title: PfSense
        entities:
          - sensor.ssl_certificate_expiry
      - type: entities
        title: Unraid
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.disk_free_unraidmntcache
          - sensor.disk_free_unraidmntuser
          - sensor.disk_free_unraidmntdisk1
          - sensor.disk_free_unraidmntdisk2
          - sensor.disk_free_unraidmntdisk3
          - sensor.disk_free_unraidmntdisk4
          - sensor.since_last_boot
      # - type: entities
      #   title: Deluge
      #   entities:
      #     - sensor.deluge_status
      #     - sensor.deluge_down_speed
          - sensor.deluge_up_speed
      - type: entities
        title: Sabnzbd
        entities:
          - sensor.sabnzbd_status
          - sensor.sabnzbd_speed
          - sensor.sabnzbd_queue_count
          - sensor.sabnzbd_queue
          - sensor.sabnzbd_left
          - sensor.sabnzbd_disk
          - sensor.sabnzbd_disk_free
      - type: entities
        title: Devices
        entities:
          - binary_sensor.family_room_thermostat_online
      - type: custom:monster-card
        card:
          title: Z-Wave
          type: glance
        filter:
          include:
            - domain: zwave
      - type: custom:monster-card
        card:
          title: Automations
        filter:
          include:
            - domain: automation
      - type: custom:tracker-card
        title: Custom Components
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

  - title: Financial
    tab_icon: mdi:currency-usd
    cards:
      - type: entities
        title: Speedtest
        entities:
          - sensor.personal_capital_assets
          - sensor.personal_capital_cash
          - sensor.personal_capital_credit
          - sensor.personal_capital_investments
          - sensor.personal_capital_liabilities
          - sensor.personal_capital_loans
          - sensor.personal_capital_mortgages
          - sensor.personal_capital_networth
          - sensor.personal_capital_other_assets

  - tab_icon: mdi:android-debug-bridge
    title: Debugging
    cards:
      - type: custom:monster-card
        card:
          title: All entities
        filter:
          include: [{}]
