resources:
# Non HACs Managed
  - type: module
    url: /local/lovelace/power-wheel-card/power-wheel-card.js?v=0.0.12
  - type: module
    url: /local/lovelace/weather-card-chart/custom-weather-card-chart.js?v=1
# Managed by HACs
  - type: module
    url: /local/community/pc-card/pc-card.js?v=0.0.3
  - type: module
    url: /local/community/mini-graph-card/mini-graph-card-bundle.js?v=0.6.0
  - type: module
    url: /local/community/mini-media-player/mini-media-player-bundle.js?v=1.3.0
  - type: js
    url: /local/community/button-entity-row/button-entity-row.js?v=1
  - type: js
    url: /local/community/monster-card/monster-card.js?v=0.2.4
  - type: js
    url: /local/community/upcoming-media-card/upcoming-media-card.js?v=0.4.0
  - type: js
    url: /local/community/lovelace-card-tools/card-tools.js?v=0.4.2
  - type: js
    url: /local/community/lovelace-more-info-card/more-info-card.js?v=1
  - type: js
    url: /local/community/lovelace-slider-entity-row/slider-entity-row.js?v=6
  - type: js
    url: /local/community/lovelace-layout-card/layout-card.js?v=1
  - type: js
    url: /local/community/lovelace-swipe-navigation/swipe-navigation.js?v=1.2.1
  - type: js
    url: /local/community/simple-thermostat/simple-thermostat.js?v=0.25.0
  - type: js
    url: /local/community/lovelace-home-feed-card/home-feed-card.js?v=0.2.8

title: Misty Way
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/solar.yaml
  - !include lovelace/views/floor-one.yaml
  - !include lovelace/views/floor-two.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/weather.yaml
  - !include lovelace/views/finance.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/settings.yaml
