camera_motion:
  alias: Camera Motion Detected
  sequence:
    - service: camera.snapshot
      data_template:
        entity_id: >-
          {% if cameraNum == 3 %}
            camera.living_room
          {% elif cameraNum == 4 %}
            camera.garage
          {% elif cameraNum == 5 %}
            camera.driveway
          {% endif %}
        filename: '/config/www/snapshots/{{cameraNum}}.jpg'
    - service: notify.mobile_app_pixel_2
      data_template:
        message: '{{ camera }} detected motion {{ now().strftime("%H:%M") }}'
        title: 'Motion Detected'
        data:
          android:
            notification:
              image: !secret camera_snapshot_url

camera_motion_enable:
  alias: Enable Camera Motion
  sequence:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.camera_garage_motion_detection
          - switch.camera_living_motion_detection
          - switch.camera_driveway_motion_detection

camera_motion_disable:
  alias: Disable Camera Motion
  sequence:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.camera_garage_motion_detection
          - switch.camera_living_motion_detection
          - switch.camera_driveway_motion_detection
