goodmorning:
  alias: goodmorning
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleeping
    - alias: "Check if dark"
      choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.dark_outside
              state:  'on'
          sequence:
            - service: switch.turn_on
              data:
                entity_id:
                  - switch.living_room_corner
                  - switch.living_room_stairs
            - service: scene.turn_on
              target:
                  entity_id: scene.kitchen_default
