goodmorning:
  alias: goodmorning
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleeping
    
    - service: switch.turn_on
      data:
        entity_id:
          - switch.living_room_corner
          - switch.living_room_stairs

    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_up
          - light.kitchen_down
        brightness: 183
        rgb_color: [255, 255, 145]
