goodmorning:
  alias: goodmorning
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleeping
    - service: script.camera_motion_disable
    - service: script.kitchen_on
    - service: script.livingroom_on
