goodnight:
  alias: goodnight
  sequence:
######################## Garge Door #####################
    - service: cover.close_cover
      data:
        entity_id: cover.garage_door_opener
######################## TV #############################
    - service: media_player.turn_off
      data:
        entity_id: media_player.living_room_tv
######################## Cache Cleanup ##################
    - service: tts.clear_cache

    - service: script.kitchen_off
    - service: script.livingroom_off
    - service: script.outside_off
    # Need to make sure lights are really out before we start looking for motion.
    - delay:
        minutes: 1
    - service: script.camera_motion_enable

####################### Set Sleeping #####################
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sleeping