kitchen_off:
  alias: Kitchen - Off
  sequence:
    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_down
          - light.kitchen_up

kitchen_on:
  alias: Kitchen - On
  sequence:
    - service: light.turn_on
      entity_id:
        - light.kitchen_up
        - light.kitchen_down
      data:
        brightness: 183
        rgb_color: [255, 255, 145]
