livingroom_off:
  alias: Livingroom - Off
  sequence:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.living_room_corner
          - switch.living_room_stairs

livingroom_on:
  alias: Livingroom - On
  sequence:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.living_room_corner
          - switch.living_room_stairs
