outside_off:
  alias: Outside - Off
  sequence:
    - service: light.turn_off
      data:
        entity_id:
          - light.front_door
          - light.garage_leds
          - light.porch_leds
    - service: switch.turn_off
      data:
        entity_id:
          - switch.driveway_light
          - switch.porch_light

outside_on:
  alias: Outside - On
  sequence:
    - service: light.turn_on
      data:
        entity_id:
          - light.garage_leds
          - light.porch_leds
        effect: Twinkle #Can Lights
        brightness_pct: 100
        rgb_color:
          - 255 # Red=100% 
          - 227 # Green=89%
          - 145 # Blue=57%
    - service: switch.turn_on
      data:
        entity_id:
          - switch.porch_light
          - switch.driveway_light
