title: Settings
icon: 'mdi:settings'
tab_icon: 'mdi:harddisk'
badges: []
cards:
  - type: horizontal-stack
    cards:
      - title: Download
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 48
        points_per_hour: 0.25
        entities:
          - entity: sensor.speedtest_download
            name: Download

      - title: Upload
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 48
        points_per_hour: 0.25
        entities:
          - entity: sensor.speedtest_upload
            name: Upload

      - title: Ping
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 48
        points_per_hour: 0.25
        entities:
          - entity: sensor.speedtest_ping
            name: Upload

  - title: PfSense
    type: entities
    show_header_toggle: false
    entities:
      - sensor.ssl_certificate_expiry
    
  - title: Unraid
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.processor_use
      - entity: sensor.memory_use_percent
      - entity: sensor.disk_free_unraid_mnt_cache
      - entity: sensor.disk_free_unraid_mnt_user
      - entity: sensor.disk_free_unraid_mnt_disk1
      - entity: sensor.disk_free_unraid_mnt_disk2
      - entity: sensor.disk_free_unraid_mnt_disk3
      - entity: sensor.disk_free_unraid_mnt_disk4
      - entity: sensor.last_boot

  - title: HACS
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.hacs

  - title: Sabnzbd
    type: entities
    show_header_toggle: false
    entities:
      - sensor.sabnzbd_status
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_queue_count
      - sensor.sabnzbd_queue
      - sensor.sabnzbd_left
      - sensor.sabnzbd_disk
      - sensor.sabnzbd_disk_free
    
  - title: Devices
    type: entities
    show_header_toggle: false
    entities:
      - entity: binary_sensor.family_room_thermostat_online
      - entity: switch.gaming_pc

  - type: 'custom:monster-card'
    card:
      title: Z-Wave
      type: glance
    filter:
      include:
        - domain: zwave
  - type: 'custom:monster-card'
    card:
      title: Automations
      type: entities
    filter:
      include:
        - domain: automation
  
  - type: entities
    title: Casting
    show_header_toggle: false
    entities:
      - type: cast
        name: Main
        view: '0'
