blueprint:
  name: Loop Media
  description: Keep playing a MP3 on loop until an input boolean is turned off
  domain: automation
  input:
    input_boolean:
      name: Input Boolean
      selector:
        entity:
          domain: 
            - input_boolean
            - binary_sensor
    media_player:
      name: Media Player
      selector:
        entity:
          domain: media_player
    media_url:
      name: Media Url
      selector:
        text:

mode: single
trigger:
  - platform: state
    entity_id: !input input_boolean
    to: "on"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
condition:
  - condition: state
    entity_id: !input input_boolean
    state: "on"
action:
  - if:
      - condition: state
        entity_id: !input media_player
        state: playing
    then:        
      - wait_for_trigger:
        - platform: state
          entity_id: !input media_player
          from: playing
          for: 0:00:10
  - repeat:
      until:
        - condition: state
          entity_id: !input input_boolean
          state: "off"
      sequence:
        - service: media_player.play_media
          entity_id: !input media_player
          data:
            media_content_id: !input media_url
            media_content_type: music
        - wait_for_trigger:
            - platform: state
              entity_id: !input media_player
              from: playing
              for: 0:00:10
            - platform: state
              entity_id: !input input_boolean
              to: "off"
  - service: media_player.turn_off
    entity_id: !input media_player
