- alias: '[TTS + Notification] AC Frozen'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.family_room_thermostat_hvac_state
    from: 'off'
    to: 'cooling'
    for:
      hours: 4
  action:
    - service: tts.google_translate_say
      entity_id: media_player.office_speaker
      data:
        message: 'Just a heads up, I think the AC might be frozen.'
    - service: notify.mobile_app_pixel_2
      data:
        title: 'Possible AC Issue'
        message: 'The AC has been running for 2 hours non stop.'
