- id: 40093ae1-3ed7-44bf-8054-8ad8a629e293
  alias: 'Almost Home - Shannon Almost Home'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: proximity.home_shannon
      above: '0'
      below: '2'
  condition:
    - condition: template
      value_template: '{{ states.proximity.home_shannon.attributes.dir_of_travel == "towards" }}'
  action:
    - service: tts.google_translate_say
      entity_id: media_player.kitchen_display
      data:
        message: Shannon is almost home!

- id: 34b1357f-3b64-44ed-b269-2206a6a3b217
  alias: 'Almost Home - Justin Almost Home'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: proximity.home_justin
      above: '0'
      below: '2'
  condition:
    - condition: template
      value_template: '{{ states.proximity.home_justin.attributes.dir_of_travel == "towards" }}'
  action:
    - service: tts.google_translate_say
      entity_id: media_player.kitchen_display
      data:
        message: Justin is almost home!
