- id: 6cf596d9-0cff-40ee-90fc-71aa64dddff2
  alias: Bolt - Plug Me In
  initial_state: 'on'
  trigger:
    - platform: time
      at: "21:00:00"
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'on'
  condition:
    - condition: state
      entity_id: device_tracker.bolt
      state: home
    - condition: numeric_state
      entity_id: sensor.bolt_soc
      below: 60
    - condition: state
      entity_id: binary_sensor.bolt_charging
      state: 'off'
  action:
    - service: notify.mobile_app_pixel_2
      data:
        message: Bolt is currently at {{ states.sensor.bolt_soc.state }}%
        title: Don't Forget to Charge
    - service: tts.google_translate_say
      entity_id: 
        - media_player.kitchen_display
        - media_player.office_speaker
        - media_player.master_bedroom_speaker
      data_template:
        cache: false
        message: "The bolt isn't charging and is only at {{ states.sensor.bolt_soc.state | round }} percent."

- id: 59095d08-adb2-4ee1-be4f-adce49b1feca
  alias: Bolt - Location Update
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.bolt_raw
  action:
    - service: device_tracker.see
      data_template:
        dev_id: bolt
        gps_accuracy: 50
        gps:
          - "{{ state_attr('sensor.bolt_raw', 'lat') }}"
          - "{{ state_attr('sensor.bolt_raw', 'lon') }}"
