- id: 7c1e31f8-c6ed-44d5-87ca-719525873df0
  alias: Cameras - Disable Motion
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: disable_cameras
    - platform: state
      entity_id: sensor.home_status
      from: 'Unoccupied'
      to: 'Occupied'
  condition: []
  action:
    - service: switch.turn_off
      entity_id: switch.motion_detection

- alias: Cameras - Enable Motion
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:  
        minutes: 6
  action:
    - service: switch.turn_on
      entity_id: switch.motion_detection
