- id: 0429efd9-4d5d-496b-ab29-fc9c50bf564e
  alias: Dark - True
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.sleeping
      from: 'on'
      to: 'off'
  condition: 
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: binary_sensor.dark_outside
      state: 'on'
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: sensor.home_status
          state:  'Occupied'
        - condition: not
          conditions:  
            - condition: state
              entity_id: media_player.plex_living_room_tv
              state: playing
        sequence:        
          - service: switch.turn_on
            data:
              entity_id:
                - switch.living_room_corner
                - switch.living_room_stairs
          - service: scene.turn_on
            data:
              entity_id: 
                - scene.kitchen_default
              transition: 60
    - service: switch.turn_on
      data:
        entity_id:
          - switch.driveway_lights
          - switch.porch_lights

- id: 9a78d5fe-bdb9-4b47-87af-67ccb7dd6efd
  alias: Dark - False
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      from: 'on'
      to: 'off'
  condition: []
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.living_room_corner
          - switch.living_room_stairs
          - switch.driveway_lights
          - switch.porch_lights
    - service: scene.turn_on
      data:
        entity_id: 
          - scene.kitchen_off
        transition: 60
