- id: 3801c24c-e453-48f8-abc0-90b67f6b7d18
  alias: Fire - Open Job
  description: ''
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.bryx_open_job
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: tts.google_translate_say
      data:
        entity_id:
          - media_player.kitchen_display
          - media_player.office_speaker
          - media_player.master_bedroom_speaker
        cache: false
        message: "Alert: {{ states('sensor.bryx_current_job_type') }} {{ states('sensor.bryx_current_job_synopsis') }} at {{ states('sensor.bryx_current_job_address') }}"
    - service: scene.turn_on
      data:
        entity_id: 
          - scene.kitchen_fire_call
        transition: 10
    - delay:
        seconds: 15
    - service: media_player.play_media
      data:
        entity_id: 
          - media_player.office_speaker
          - media_player.kitchen_display
        media_content_id: "{{states('sensor.wcf_scanner_stream')}}"
        media_content_type: music
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.bryx_open_job
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    - service: media_player.media_stop
      data:
        entity_id: 
          - media_player.office_speaker
          - media_player.kitchen_display
    - service: scene.turn_on
      data:
        entity_id: 
          - scene.kitchen_default
        transition: 10
