- id: 3801c24c-e453-48f8-abc0-90b67f6b7d18
  alias: Fire - Open Job
  description: ''
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bryx_open_job
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: tts.google_translate_say
      data:
        entity_id:
          - media_player.kitchen_display
          - media_player.office_speaker
          - media_player.master_bedroom_speaker
        cache: false
        message: "Alert: {{ states('sensor.bryx_current_job_type') }} {{ states('sensor.bryx_current_job_synopsis') }} at {{ states('sensor.bryx_current_job_address') }}"
    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_up
          - light.kitchen_down
        brightness: 255
        rgb_color: [255, 0, 0]
