- id: 30424b67-a4c9-4da2-a1c3-1cf63f48ada3
  alias: Furnace - AC Frozen
  trigger:
    platform: state
    entity_id: sensor.family_room_thermostat_hvac_state
    from: 'off'
    to: 'cooling'
    for:
      hours: 4
  action:
    - service: tts.google_translate_say
      entity_id: media_player.office_speaker
      data:
        message: 'Just a heads up, I think the AC might be frozen.'
    - service: notify.mobile_app_pixel_4a
      data:
        title: 'Possible AC Issue'
        message: 'The AC has been running for 2 hours non stop.'
        data:
          channel: Critical

- id: cd89cab1-5e0a-4b74-bd3f-59c7f11c64af
  alias: Furnace - Away Mode
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:  
        minutes: 5
  action:
    - service: nest.set_away_mode
      data:
        away_mode: away

- id: dff2efb3-c16c-46d9-9f8f-56e920ea1a06
  alias: Furnace - Home Mode
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Occupied'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home


