- id: '1523975149744'
  alias: 'Garage Door - Left Open Notification'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
  condition:
    - condition: state
      entity_id: cover.garage_door_opener
      state: open
  action:
    - service: notify.mobile_app_pixel_2
      data:
        message: Looks like the garage was left open!! {{ now().strftime("%H:%M") }}
        title: Garage left open!
        data:
          actions:
          - action: close_garage
            title: Close Door

- id: '1523975760898'
  alias: 'Garage Door - Close'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: close_garage
  condition: []
  action:
    - service: cover.close_cover
      data:
        entity_id: cover.garage_door_opener

- id: '1524146043949'
  alias: 'Garage Door - Almost Home Notification'
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: proximity.home_justin
    above: '0'
    below: '2'
  condition:
    - condition: state
      entity_id: cover.garage_door_opener
      state: closed
    - condition: template
      value_template: '{{ states.proximity.home_justin.attributes.dir_of_travel == "towards" }}'
  action:
    - service: notify.mobile_app_pixel_2
      data:
        title: Almost Home!
        message: Would you like to open the garage door?
        data:
          actions:
            - title: Open Door
              action: open_garage

- id: '1524146180812'
  alias: 'Garage Door - Open'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: open_garage
  condition: []
  action:
    - service: cover.open_cover
      data:
        entity_id: cover.garage_door_opener


- id: '1524579938313'
  alias: 'Garage Door - Opened/Closed not home'
  initial_state: 'on'
  trigger:
    - entity_id: cover.garage_door_opener
      platform: state
      from: Open
      to: Closed
    - entity_id: cover.garage_door_opener
      platform: state
      from: Closed
      to: Open
  condition:
    - condition: state
      entity_id: group.home_status
      state: Unoccupied
  action:
    - service: notify.mobile_app_pixel_2
      data:
        title: 'Garage Door: {{ states(''cover.garage_door_opener'') }}'
        message: Garage is now {{ states('cover.garage_door_opener') }} at {{ now().strftime("%H:%M") }}
        data:
          actions:
            - action: close_garage
              title: Close Door
            - action: open_garage
              title: Open Door