- id: 8c854893-f82c-4fe5-9d37-d3d6f36f89b1
  alias: Harrison - Sleep
  initial_state: 'on'
  trigger:
    # Start times
    - platform: time
      at: 
        - '11:45:00'
        - '18:30:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: Occupied
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.harrison_nap
    - service: automation.trigger
      data:
        entity_id: automation.harrison_fan_control

- id: 65b05a5e-aa84-4ee7-8758-27927054b049
  alias: Harrison - Keep Sleeping
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.harrison_nap
      to: 'on'
    - platform: state
      entity_id: media_player.harrisons_room_speaker
      from: 'playing'
      for:
        seconds: 10
  condition:
    - condition: state
      entity_id: input_boolean.harrison_nap
      state: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.harrisons_room_speaker
        media_content_id: !secret ocean_sounds_url
        media_content_type: 'music'

- id: 71ff4a11-7a4d-4f49-9d8e-de8b024feaa6
  alias: Harrison - Wakup
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.harrison_nap
      to: 'off'
    - platform: time
      at: '16:00:00'
    - platform: time
      at: '08:30:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.harrison_nap
    - service: media_player.turn_off
      data:
        entity_id: media_player.harrisons_room_speaker
    - service: fan.turn_off
      data:
        entity_id: fan.harrison

- id: 8880f282-3b23-48ad-b9d8-34c83abb535c
  alias: Harrison - Fan Control
  initial_state: 'on'
  trigger:
    # This doesn't update too much, should be safe
    - platform: state
      entity_id: sensor.harrison_temperature
  condition:
    - condition: state
      entity_id: input_boolean.harrison_nap
      state: 'on'
    - condition: state
      entity_id: sensor.family_room_thermostat_operation_mode
      state: 'cool'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.harrison
        speed: >
          {%set diff=states('sensor.harrison_temperature')|float - state_attr('climate.family_room', 'current_temperature')|float%}
          {% if diff < 2 %}
            off
          {% elif diff < 4 %}
            low
          {% elif diff < 6 %}
            medium
          {% else %}
            high
          {% endif%}
