- alias: 'Kids - Weston Sleep'
  initial_state: 'on'
  trigger:
    # Start times
    - platform: time
      at: '11:45:00'
    - platform: time
      at: '19:45:00'
    - platform: state
      entity_id: sensor.home_status
      from: Unoccupied
      to: Occupied
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: Occupied
    - condition: or
      conditions:
        - condition: time
          after: '11:45:00'
          before: '16:00:00'
        - condition: time
          after: '19:45:00'
          before: '08:30:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.weston_nap
    - service: automation.trigger
      data:
        entity_id: automation.weston_fan_control

- alias: 'Kids - Weston Keep Sleeping'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.weston_nap
      to: 'on'
    - platform: state
      entity_id: media_player.westons_room_speaker
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.weston_nap
      state: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.westons_room_speaker
        media_content_id: !secret babbling_brook_url
        media_content_type: 'music'

- alias: 'Kids - Weston Wakup'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.weston_nap
      to: 'off'
    - platform: time
      at: '16:00:00'
    - platform: time
      at: '08:30:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weston_nap
    - service: media_player.turn_off
      data:
        entity_id: media_player.westons_room_speaker
    - service: fan.turn_off
      data:
        entity_id: fan.weston_fan

- alias: 'Kids - Weston Fan Control'
  initial_state: 'on'
  trigger:
    # This doesn't update too much, should be safe
    - platform: state
      entity_id: sensor.weston_temperature
  condition:
    - condition: state
      entity_id: input_boolean.weston_nap
      state: 'on'
    - condition: state
      entity_id: sensor.family_room_thermostat_operation_mode
      state: 'cool'
  action:
    - service: fan.set_speed
      data_template:
        entity_id: fan.weston_fan
        speed: >
          {%set diff=states('sensor.weston_temperature')|float - state_attr('climate.family_room', 'current_temperature')|float%}
          {% if diff < 2 %}
            off
          {% elif diff < 4 %}
            low
          {% elif diff < 6 %}
            medium
          {% else %}
            high
          {% endif%}

#################### Harrison ####################
- alias: 'Kids - Harrison Keep Sleeping'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.harrison_nap
      to: 'on'
    - platform: state
      entity_id: media_player.harrisons_room_speaker
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.harrison_nap
      state: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.harrisons_room_speaker
        media_content_id: !secret babbling_brook_url
        media_content_type: 'music'

- alias: 'Kids - Harrison Wakup'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.harrison_nap
      to: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.harrison_nap
    - service: media_player.turn_off
      data:
        entity_id: media_player.harrisons_room_speaker
    - service: fan.turn_off
      data:
        entity_id: fan.harrison_fan
