- id: 032ae0b0-aec1-47f8-bd52-465174b0912d
  alias: 'Kitchen - On'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dark_outside
      to: 'on'
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'off'
    - platform: state
      entity_id: sensor.home_status
      to: 'Occupied'
  condition:
    - condition: state
      entity_id: input_boolean.dark_outside
      state: 'on'
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: script.kitchen_on

- id: 2ae182a7-3703-4af9-b558-a2ea6e4e1a88
  alias: 'Kitchen - Off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dark_outside
      to: 'off'
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'on'
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:  
        minutes: 5
  action:
    - service: script.kitchen_off
