- id: 9ca74552-958b-43bb-a399-1882cd4864fd
  alias: 'Livingroom - On'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dark_outside
      to: 'on'
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'off'
    - platform: state
      entity_id: sensor.home_status
      to: 'Occupied'
  condition:
    - condition: state
      entity_id: input_boolean.dark_outside
      state: 'on'
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: script.livingroom_on

- id: d562ae13-faff-4392-bf0d-194e96eedaa5
  alias: 'Livingroom - Off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dark_outside
      to: 'off'
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'on'
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:  
        minutes: 5
  action:
    - service: script.livingroom_off

- id: f4442aab-21d6-4ee1-ac21-a3de30bdee0f
  alias: 'Livingroom - Fireplace Fan'
  initial_state: 'on'
  mode: restart
  trigger:
    - platform: state
      entity_id: switch.fireplace_flame
      to: 'off'
  action:
    - delay:
        minutes: 10
    - service: switch.turn_off
      data:
        entity_id: switch.fireplace_fan
