- id: a212fb84-d631-4227-a434-54df8801b915
  alias: Maintenance - HA Update Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.mobile_app_pixel_4a
      data:
        title: 'New Home Assistant Release'
        message: "Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version') }}  is now available."
        data:
          channel: Updates

- id: 35d10f53-5a94-468c-bce2-152c2903bda3
  alias: Maintenance - HACS Update Notification
  trigger:
    - platform: state
      entity_id: sensor.hacs
  condition:
    - condition: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: notify.mobile_app_pixel_4a
      data:
        title: 'New HACS Componenet Release'
        message: >-
          Updates ready for: 
          {% for repo in states.sensor.hacs.attributes.repositories -%} 
            {{repo.display_name}}{%- if not loop.last %}, {% endif -%}
          {%- endfor %}
        data:
          channel: Updates
          tag: HACS

- id: 315d8975-7f69-4348-b191-31ec1608d3d8
  alias: Maintenance - HACS Clear Update Notification
  trigger:
    - platform: state
      entity_id: sensor.hacs
      to: "0"
  condition: []
  action:
    - service: notify.mobile_app_pixel_4a
      data:
        message: clear_notification
        data:
          tag: HACS

- id: 41b69fce-9657-4d1f-9ab9-6c72caf45eb0
  alias: Maintenance - Resync Google Assistant
  trigger:
    - platform: time
      at: "12:15:00"
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: google_assistant.request_sync
      data:
        agent_user_id: !secret userid_justin

- id: c80dcad1-3364-4c87-81a4-fecb1a438a3e
  alias: Maintenance - Internet Speeds Slow
  trigger:
    - platform: numeric_state
      entity_id: sensor.speedtest_download
      below: 150
  action:
    - delay:
        minutes: 5
    - service: speedtestdotnet.speedtest
    - wait_for_trigger:
      - platform: state
        entity_id: sensor.speedtest_download
    - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.speedtest_download
            below: 150
        sequence:
          - service: notify.mobile_app_pixel_4a
            data:
              title: Slow Internet
              message: "Your internet speed is only {{ states('sensor.speedtest_download') }} Mbit/s"
