- alias: 'Schedule - Wake Up'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: script.goodmorning


- alias: 'Schedule - Bedtime'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:30:00'
  action:
    - service: script.goodnight
