- id: 80b144d9-d108-4f29-a7cd-01c730e7b8ea
  alias: 'Schedule - Wake Up'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:15:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: script.goodmorning


- id: 775bbb47-3e20-4c6f-bf19-b2c8d232490b
  alias: 'Schedule - Bedtime'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:30:00'
  action:
    - service: script.goodnight
