- id: bb6ed2ee-4122-4f8d-afc6-cad61dedfec9
  alias: Solar - Dark Outside
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_raw_total_power
      below: .8
      for:
        minutes: 5
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dark_outside

- id: 441c26de-4081-463f-8625-1ec0035e0846
  alias: Solar - Bright Outside
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_raw_total_power
      above: .8
      for:
        minutes: 5
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dark_outside
