- alias: '[TTS] New TV Episode'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: TV_EPISODE_DOWNLOADED
    event_data: {}
  condition:
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
    # Make sure we aren't already watching something on the tv
    - condition: template
      value_template: "{{ states.media_player.living_room_tv.state != 'playing' }}"
    # Make sure we aren't already watching something on the home
    - condition: template
      value_template: "{{ states.media_player.living_room_speaker.state != 'playing' }}"
  action:
  - service: tts.google_translate_say
    entity_id: media_player.living_room_speaker
    data_template:
      message: 'Good news, I downloaded a new episode of {{ trigger.event.data["title"] }}.'
