- id: 52c69177-2d5d-4c19-9df8-af7730a44478
  alias: 'SpaceX - Next Launch Time Updated'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.next_launch_day
      attribute: launch_date_unix
      above: 946684800 # January 1, 2000
    - platform: homeassistant
      event: start
  action:
    # 30 minutes before
    - service: input_datetime.set_datetime
      data:
        entity_id: input_datetime.spacex_notification_push_time
        timestamp: "{{ state_attr('sensor.next_launch_day', 'launch_date_unix') - 1800 }}"
    # 5 minutes before
    - service: input_datetime.set_datetime
      data:
        entity_id: input_datetime.spacex_notification_tts_time
        timestamp: "{{ state_attr('sensor.next_launch_day', 'launch_date_unix') - 300 }}"

- id: c43a47e8-ce29-4ac0-b6ff-cbc35f13acb9
  alias: 'SpaceX - Push Notification'
  initial_state: 'on'
  trigger:
    - platform: time
      at: input_datetime.spacex_notification_push_time
  action:
    - service: notify.mobile_app_pixel_2
      data:
        message: SpaceX will be launching at {{ states.sensor.spacex.state | int | timestamp_local }}
        title: SpaceX Launch Soon
        data:
          clickAction: "{{ states.sensor.spacex.attributes.links.video_link }}"
    - service: automation.turn_on
      data: 
        entity_id: automation.spacex_tts

- id: 20c8c7d2-fdb3-443d-89f6-6ad2d7449b12
  alias: 'SpaceX - TTS'
  initial_state: 'on'
  trigger:
    - platform: time
      at: input_datetime.spacex_notification_tts_time
  action:
    - service: tts.google_translate_say
      entity_id: 
        - media_player.office_speaker
        - media_player.kitchen_display
      data:
        message: 'SpaceX will be launching in less than 10 minutes!'

    - service: notify.mobile_app_pixel_2
      data:
        message: SpaceX final countdown!
        title: SpaceX Launch Imminent
        data:
          clickAction: "{{ states.sensor.spacex.attributes.links.video_link }}"
    - service: automation.turn_off
      data: 
        entity_id: automation.spacex_tts
