- id: c43a47e8-ce29-4ac0-b6ff-cbc35f13acb9
  alias: 'SpaceX - Push Notification'
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: "/15"
  condition:
    # Hourish before launch
    - condition: template
      value_template: "{{ as_timestamp(now()) > (states.sensor.spacex.state | int) - 3600 }}"
    - condition: template
      value_template: "{{ as_timestamp(now()) <= (states.sensor.spacex.state | int) - 2700 }}"
  action:
    - service: notify.mobile_app_pixel_2
      data:
        message: SpaceX will be launching at {{ states.sensor.spacex.state | int | timestamp_local }}
        title: SpaceX Launch Soon
        data:
          clickAction: "{{ states.sensor.spacex.attributes.links.video_link }}"
    - service: automation.turn_on
      data: 
        entity_id: automation.spacex_tts

- id: 20c8c7d2-fdb3-443d-89f6-6ad2d7449b12
  alias: 'SpaceX - TTS'
  initial_state: 'off'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) > (states.sensor.spacex.state | int) - 600 }}"
  action:
    - service: tts.google_translate_say
      entity_id: 
        - media_player.office_speaker
        - media_player.kitchen_display
      data:
        message: 'SpaceX will be launching in less than 10 minutes!'

    - service: notify.mobile_app_pixel_2
      data:
        message: SpaceX final countdown!
        title: SpaceX Launch Imminent
        data:
          clickAction: "{{ states.sensor.spacex.attributes.links.video_link }}"
    - service: automation.turn_off
      data: 
        entity_id: automation.spacex_tts
