- alias: 'Sun - Morning Routine'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
    - condition: sun
      before: sunrise
  action:
    - service: script.camera_motion_disable
    - delay:
        minutes: 1
    - service: script.kitchen_on
    - service: script.livingroom_on

- alias: 'Sun - Sunrise Routine'
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunrise
      offset: '+1:30:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dark_outside
    - service: script.kitchen_off
    - service: script.livingroom_off
    - service: script.outside_off

- alias: 'Sun - Sunset Routine'
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-1:15:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dark_outside
    - service: script.outside_on
    ## Only continue if occupied
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'

    - service: script.kitchen_on
    - service: script.livingroom_on

- alias: 'Sun - Bedtime Routine'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:30:00'
  action:
    - service: script.goodnight
