- alias: 'Theater - Starting Media'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      to: playing
  condition:
    - condition: state
      entity_id: input_boolean.dark_outside
      state:  'on'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.living_room_outlet_corner
        - switch.living_room_outlet_stairs
    - service: light.turn_on
      entity_id:
        - light.kitchen_up
        - light.kitchen_down
      data:
        rgb_color: [255, 255, 145]
        brightness_pct: 25

- alias: 'Theater - Stopping Media'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: playing
  condition:
    - condition: state
      entity_id: input_boolean.dark_outside
      state:  'on'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.living_room_outlet_corner
        - switch.living_room_outlet_stairs
    - service: script.kitchen_on
