- id: ab41d20f-5788-413c-8f5a-93ad5a92b6e3
  alias: 'Theater - Starting Media'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      to: playing
  condition:
    - condition: state
      entity_id: input_boolean.dark_outside
      state:  'on'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.living_room_corner
          - switch.living_room_stairs
    - choose:
      - conditions: "{{ (state_attr('media_player.plex_living_room_tv', 'media_content_type')) == 'movie' }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.kitchen_up
                - light.kitchen_down
              rgb_color: [255, 255, 145]
              brightness_pct: 25

- id: b218303e-bbd7-405b-842a-9b1909ff848b
  alias: 'Theater - Stopping Media'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_tv
      from: playing
      for:
        seconds: 5
  condition:
    - condition: state
      entity_id: input_boolean.dark_outside
      state:  'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.living_room_corner
          - switch.living_room_stairs

    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_up
          - light.kitchen_down
        brightness: 183
        rgb_color: [255, 255, 145]
