- id: ee48101c-720f-4d4d-84c4-796f3a3eb424
  alias: Weston - Sleep
  initial_state: 'on'
  trigger:
    # Start times
    - platform: time
      at: 
        - '11:45:00'
        - '19:15:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: Occupied
    - condition: not
      conditions:    
      - condition: time
        after: '08:00:00'
        before: '17:00:00'
        weekday:
          - tue
          - thu
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.weston_nap
    - service: automation.trigger
      data:
        entity_id: automation.weston_fan_control

- id: 9d684000-821b-49c3-9770-3fa876b6effb
  alias: Weston - Keep Sleeping
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.weston_nap
      to: 'on'
    - platform: state
      entity_id: media_player.westons_room_speaker
      from: 'playing'
      for:
        seconds: 10
  condition:
    - condition: state
      entity_id: input_boolean.weston_nap
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.weston_lamp
        brightness: 3
        rgb_color: [255, 0, 0]
    - service: media_player.play_media
      data:
        entity_id: media_player.westons_room_speaker
        media_content_id: !secret ocean_sounds_url
        media_content_type: 'music'
    # - service: media_player.play_media
    #   data:
    #     entity_id: media_player.westons_room_speaker
    #     media_content_type: MUSIC
    #     media_content_id: >-
    #       plex://{ 
    #         "library_name": "Music", 
    #         "artist_name": "Raffi",
    #         "shuffle": "1"
    #       }


- id: 8ab6d2cd-32fa-494f-a0e8-271dda57fa04
  alias: Weston - Wakup
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.weston_nap
      to: 'off'
    - platform: time
      at: '16:00:00'
    - platform: time
      at: '08:30:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weston_nap
    - service: media_player.turn_off
      data:
        entity_id: media_player.westons_room_speaker
    - service: fan.turn_off
      data:
        entity_id: fan.weston
    - service: light.turn_off
      data:
        entity_id: light.weston_lamp

- id: d1007417-f48d-4f5c-a06e-8d712a2ef51a
  alias: Weston - Fan Control
  initial_state: 'on'
  trigger:
    # This doesn't update too much, should be safe
    - platform: state
      entity_id: sensor.weston_temperature
  condition:
    - condition: state
      entity_id: input_boolean.weston_nap
      state: 'on'
    - condition: state
      entity_id: sensor.family_room_thermostat_operation_mode
      state: 'cool'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.weston
        speed: >
          {%set diff=states('sensor.weston_temperature')|float - state_attr('climate.family_room', 'current_temperature')|float%}
          {% if diff < 2 %}
            off
          {% elif diff < 4 %}
            low
          {% elif diff < 6 %}
            medium
          {% else %}
            high
          {% endif%}
