- platform: template
  sensors:
    bolt_soc:
      friendly_name: Bolt - Current Charge
      entity_id: sensor.bolt_raw
      value_template: '{{ states["sensor.bolt_raw"].state | round(2) }}'
      unit_of_measurement: '%'
      device_class: battery
    bolt_battery_temp:
        friendly_name: Bolt - Battery Temperature
        entity_id: sensor.bolt_raw
        value_template: '{{ states["sensor.bolt_raw"].attributes.battery_temp }}'
        unit_of_measurement: '°C'
