- platform: integration
  source: sensor.bolt_house_power_consumption
  name: Bolt Home Energy Usage

- platform: template
  sensors:
    bolt_house_power_consumption:
      friendly_name: Bolt - Home Power Usage
      unit_of_measurement: 'kW'
      value_template: >
        {% set forceUpdate = states('sensor.home_energy_lifetime_net') %}
        {% set fudge = (range(0, 10) | random /1000.0 ) %}
        {% if states('device_tracker.bolt_2') == 'home' and states('binary_sensor.bolt_charging') == 'on' and states('binary_sensor.bolt_connected') == 'on' %}
          {{ (states('sensor.bolt_power')|float * -1) + fudge }}
        {% else %}
          0
        {% endif %}
