- platform: template
  sensors:
    bolt_soc:
      friendly_name: Bolt - Current Charge
      value_template: '{{ states("sensor.bolt_raw") | round(2) }}'
      unit_of_measurement: '%'
      device_class: battery
    bolt_battery_temp:
      friendly_name: Bolt - Battery Temperature
      value_template: '{{ state_attr("sensor.bolt_raw", "battery_temp") }}'
      unit_of_measurement: '°C'
    bolt_pi_voltage:
      friendly_name: Bolt - Pi Voltage
      value_template: '{{ state_attr("sensor.bolt_raw", "pi_voltage") }}'
      unit_of_measurement: 'V'
