- platform: cert_expiry
  host: !secret ha_domain

- platform: cert_expiry
  host: !secret auth_domain
  
- platform: cert_expiry
  host: !secret tv_domain
  
- platform: cert_expiry
  host: !secret movies_domain
  
- platform: cert_expiry
  host: !secret plex_domain
  
- platform: cert_expiry
  host: !secret grafana_domain
  
- platform: cert_expiry
  host: !secret security_domain
  
- platform: cert_expiry
  host: !secret unraid_domain
  
- platform: cert_expiry
  host: !secret pfsense_domain
  
- platform: cert_expiry
  host: !secret music_domain
  
- platform: cert_expiry
  host: !secret sync_domain
  
- platform: cert_expiry
  host: !secret code_domain
  
- platform: cert_expiry
  host: !secret hydra_domain
  
- platform: cert_expiry
  host: !secret usenet_domain