- platform: history_stats
  name: Pixel 4a Interactive Time Today
  entity_id: binary_sensor.pixel_4a_interactive
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S22 Interactive Time Today
  entity_id: binary_sensor.s22_interactive
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
