- platform: history_stats
  name: Pixel Fold Interactive Time Today
  entity_id: binary_sensor.pixel_fold_interactive
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Pixel 7 Interactive Time Today
  entity_id: binary_sensor.pixel_7_interactive
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
