- platform: scrape
  name: WCF Scanner Stream
  resource: https://www.broadcastify.com/webPlayer/13501
  select: audio
  attribute: src
  value_template: "{{ value.split('?')[0] }}"
  scan_interval: 600
