- platform: integration
  source: sensor.furnace_power_consumption
  name: Furnace Home Energy Usage
  unit: kWh
  method: left

- platform: template
  sensors:
    furnace_power_consumption:
      friendly_name: Furnace Power Usage
      unit_of_measurement: 'kW'
      value_template: >
        {% set forceUpdate = states('sensor.home_energy_lifetime_net') %}
        {% set fanOn = states('binary_sensor.family_room_thermostat_fan') == 'on' %}
        {% set acOn = states('sensor.family_room_thermostat_hvac_state') == 'cool' %}
        {% set fudge = (range(0, 10) | random /1000.0 ) %}
        {{ (fanOn * 0.4) + (acOn * 1.5) + ((fanOn or acOn) * fudge) }}
