- platform: rest
  # resource: https://static.nfl.com/liveupdate/scorestrip/ss.xml
  resource: http://static.nfl.com/liveupdate/scorestrip/postseason/ss.xml
  name: bills_game_status
  value_template: >
    {% for game in value_json.ss.gms.g 
      | sort(attribute="@gsis",reverse=true) 
      if game['@h'] == 'BUF' or game['@v'] == 'BUF' 
    %}
      {% if loop.first %}
        {% if game['@q'] == 'P' %}
          Pregame
        {% elif game['@q'] == '1' or game['@q'] == '2' or game['@q'] == '3' or game['@q'] == '4' or game['@q'] == 'O' or game['@q'] == 'H' %}
          In Progress
        {% elif game['@q'] == 'FO' %}
          F(OT)
        {% elif game['@q'] == 'F' %}
          Final
        {% elif game['@q'] == 'S' %}
          Suspended      
        {% endif %}        
      {% endif %}
    {% endfor %}
  json_attributes:
    - ss
  scan_interval: 
    minutes: 5
- platform: template
  sensors:
    bills_score:
      friendly_name: Bills Score
      value_template: >
        {% for game in states.sensor.bills_game_status.attributes['ss']['gms']['g'] 
          | sort(attribute="@gsis",reverse=true) 
          if game['@h'] == 'BUF' or game['@v'] == 'BUF' 
        %}
          {% if loop.first %}
            {% if game['@h'] == 'BUF' %}
              {{ game['@hs'] }}
            {% else %}
              {{ game['@vs'] }}
            {% endif %}
          {% endif %}
        {% endfor %}
    bills_quarter:
      friendly_name: Bills Quarter
      value_template: >
        {% for game in states.sensor.bills_game_status.attributes['ss']['gms']['g'] 
          | sort(attribute="@gsis",reverse=true) 
          if game['@h'] == 'BUF' or game['@v'] == 'BUF' 
        %}
          {% if loop.first %}
            {% if game['@q'] == 'P' or game['@q'] == 'S' %}
              0 
            {% elif game['@q'] == 'F' or game['@q'] == 'FO' %}
              -1
            {% elif game['@q'] == 'H' %}
              2          
            {% elif game['@q'] == 'O' %}
              5          
            {% else %}
              {{ game['@q'] }}
            {% endif %}            
          {% endif %}
        {% endfor %}
