- platform: rest
  # resource: https://static.nfl.com/liveupdate/scorestrip/ss.xml
  # resource: http://static.nfl.com/liveupdate/scorestrip/postseason/ss.xml
  resource: http://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard
  name: bills_game_status
  value_template: >
    {% for event in value_json.events %}
      {% if 'BUF' in event.shortName %}
        {{ event['status']['type']['description'] }}        
      {% endif %}
    {% endfor %}
  json_attributes:
    - events
  scan_interval: 
    minutes: 5
- platform: template
  sensors:
    bills_score:
      friendly_name: Bills Score
      value_template: >
        {% for event in states.sensor.bills_game_status.attributes['events'] %}
          {% if 'BUF' in event.shortName %}
            {% for competitor in event['competitions'][0]['competitors'] %}
              {% if 'BUF' == competitor['team']['abbreviation'] %}
                {{competitor['score']}}
              {% endif %} 
            {% endfor %}
          {% endif %}
        {% endfor %}
    bills_quarter:
      friendly_name: Bills Quarter
      value_template: >
        {% for event in states.sensor.bills_game_status.attributes['events'] %}
          {% if 'BUF' in event.shortName %}
            {{ event['status']['period'] }}
          {% endif %}
        {% endfor %}
