- platform: plex_recently_added
  host: !secret plex_ip
  token: !secret plex_token
  max: 5
  section_types:
    - movie
    - show

- platform: personalcapital
  email: !secret personalCap_user
  password: !secret personalCap_pass

- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  monitored_conditions:
    - movies
    - upcoming
    - commands
    - status
- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  days: 120

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret sonarr_ip
  port: !secret sonarr_port
  days: 2


- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /unraid/mnt/user
    - type: disk_free
      arg: /unraid/mnt/cache
    - type: disk_free
      arg: /unraid/mnt/disk1
    - type: disk_free
      arg: /unraid/mnt/disk2
    - type: disk_free
      arg: /unraid/mnt/disk3
    - type: disk_free
      arg: /unraid/mnt/disk4
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: template
  sensors:
    home_status:
      friendly_name: Home status
      value_template: >
        {% if not(
          is_state('person.justin' , 'home')
          or 
          is_state('person.shannon' , 'home') 
          or 
          is_state('input_boolean.guest_mode' , 'on')
          ) %}
          Unoccupied
        {% else %} 
          Occupied
        {% endif %}
    outdoor_temperature:
      friendly_name: Outdoor Temperature
      value_template: >
        {{state_attr('weather.dark_sky', 'temperature') | float}}
      unit_of_measurement: °F
      device_class: temperature
