- platform: plex_recently_added
  host: !secret plex_ip
  token: !secret plex_token
  max: 5
  section_types:
    - movie
    - show

- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  monitored_conditions:
    - movies
    - upcoming
    - commands
    - status
- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret radarr_ip
  port: !secret radarr_port
  days: 120

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret sonarr_ip
  port: !secret sonarr_port
  days: 2


- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /unraid/mnt/user
    - type: disk_free
      arg: /unraid/mnt/cache
    - type: disk_free
      arg: /unraid/mnt/disk1
    - type: disk_free
      arg: /unraid/mnt/disk2
    - type: disk_free
      arg: /unraid/mnt/disk3
    - type: disk_free
      arg: /unraid/mnt/disk4
    - type: disk_free
      arg: /unraid/mnt/disk5
    - type: disk_free
      arg: /unraid/mnt/disk6
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: template
  sensors:
    home_status:
      friendly_name: Home status
      value_template: >
        {% set jhome =is_state('person.justin', 'home') %}
        {% set shome =is_state('person.shannon', 'home') %}
        {% set ghome =is_state('input_boolean.guest_mode', 'on') %}
        {% set jsleep =is_state('input_boolean.justin_sleeping', 'on') %}
        {% set ssleep =is_state('input_boolean.shannon_sleeping', 'on') %}
        {% if not(jhome or shome or ghome) %}
          Unoccupied
        {% elif 
          (not jhome or jsleep)
          and
          (not shome or ssleep)
          and
          (not ghome)
        %}
          Sleeping
        {% else %}
          Occupied
        {% endif %}

- platform: template
  sensors:
    spa_time_to_temp:
      friendly_name: 'Spa - Time to Temp'
      device_class: 'timestamp'
      value_template: >-
        {% set target = state_attr('climate.spa_heater', 'temperature') %}
        {% set current = state_attr('climate.spa_heater', 'current_temperature') %}
        {% if target - current > 0 %}
          {{ as_datetime(as_timestamp(now()) + (((target-current) * 3600)/4.5)) }}
        {% endif %}
