- platform: template
  sensors:
    ha_domain:
      value_template: !secret ha_domain
    api_password:
      value_template: !secret api_password
    solar_raw_total_power:
      friendly_name: 'Raw Total Solar Power Production'
      unit_of_measurement: 'kW'
      value_template: >-
        {%- if states.sensor|selectattr('attributes.DEVICE_TYPE','equalto','Inverter')|list|length == 24 %}
          {{states.sensor|selectattr('attributes.DEVICE_TYPE','equalto','Inverter')|map(attribute='state')|map('float')|sum|round(2)}}
        {%- endif %}
    solar_raw_lifetime_net_energy:
      friendly_name: 'Lifetime Raw Net Energy'
      unit_of_measurement: 'kWh'
      value_template: >-
        {{state_attr('sensor.solar_consumptionmeter_pvs5m644235c', 'net_ltea_3phsum_kwh')}}
    solar_raw_house_usage:
      friendly_name: 'Raw Current House Power Usage'
      unit_of_measurement: 'kW'
      value_template: >-
        {%- if states('sensor.solar_raw_total_power') is defined and states('sensor.solar_consumptionmeter_pvs5m644235c') is defined %}
          {{(states('sensor.solar_raw_total_power')|float + states('sensor.solar_consumptionmeter_pvs5m644235c')|float)|round(2)}}
        {%- endif -%}
    # solar_house_usage:
    #   friendly_name: 'Current House Power Usage'
    #   unit_of_measurement: 'kW'
    #   value_template: >-
    #     {%- if states('sensor.incoming_solar_power') is defined and states('sensor.current_consumption_meter') is defined %}
    #       {{(states('sensor.incoming_solar_power')|float + states('sensor.current_consumption_meter')|float)|round(2)}}
    #     {%- endif -%}
        
# - platform: filter
#   name: 'Current Consumption Meter'
#   entity_id: sensor.solar_consumptionmeter_pvs5m644235c
#   filters:
#     - filter: lowpass
#       precision: 2
# - platform: filter
#   name: 'Incoming Solar Power'
#   entity_id: sensor.solar_raw_total_power
#   filters:
#     - filter: lowpass
#       precision: 2
      
- platform: speedtest
  minute:
    - 21
  monitored_conditions:
    - ping
    - download
    - upload

- platform: plex
  host: !secret plex_host
  username: !secret plex_user
  password: !secret plex_pass
  token: !secret plex_token

- platform: lyft
  client_id: !secret lyft_client
  client_secret: !secret lyft_secret
  start_latitude: !secret home_lat
  start_longitude: !secret home_lon
  end_latitude: 43.12771            # ROC Airport
  end_longitude: -77.6690977

- platform: uber
  server_token: !secret uber_token
  start_latitude: !secret home_lat
  start_longitude: !secret home_lon
  end_latitude: 43.12771            # ROC Airport
  end_longitude: -77.6690977

- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_host
  port: !secret radarr_port
  monitored_conditions:
    - movies
    - upcoming
    - commands
    - status
- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret radarr_host
  port: !secret radarr_port
  days: 120

- platform: sonarr
  api_key: !secret sonarr_api
  host: !secret sonarr_host
  port: !secret sonarr_port
  monitored_conditions:
    - upcoming
    - wanted
    - commands
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret sonarr_host
  port: !secret sonarr_port
  days: 2


# - platform: deluge
#   host: !secret deluge_host
#   username: !secret deluge_user
#   password: !secret deluge_pass
#   monitored_variables:
#     - 'current_status'
#     - 'download_speed'
#     - 'upload_speed'

- platform: cert_expiry
  host: !secret root_domian

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /unraid/mnt/user
    - type: disk_free
      arg: /unraid/mnt/cache
    - type: disk_free
      arg: /unraid/mnt/disk1
    - type: disk_free
      arg: /unraid/mnt/disk2
    - type: disk_free
      arg: /unraid/mnt/disk3
    - type: disk_free
      arg: /unraid/mnt/disk4
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot

# - platform: sunpower
#   username: !secret sunpower_user
#   password: !secret sunpower_pass
#   monitored_conditions:
#     - energyProduction
#     - energyConsumption
#     - powerProduction
#     - powerConsumption
