- platform: speedtest
  minute:
    - 21
  monitored_conditions:
    - ping
    - download
    - upload

- platform: plex
  host: !secret plex_host
  username: !secret plex_user
  password: !secret plex_pass
  token: !secret plex_token

- platform: lyft
  client_id: !secret lyft_client
  client_secret: !secret lyft_secret
  start_latitude: !secret home_lat
  start_longitude: !secret home_lon
  end_latitude: 43.12771            # ROC Airport
  end_longitude: -77.6690977

- platform: uber
  server_token: !secret uber_token
  start_latitude: !secret home_lat
  start_longitude: !secret home_lon
  end_latitude: 43.12771            # ROC Airport
  end_longitude: -77.6690977

- platform: radarr
  api_key: !secret radarr_api
  host: !secret radarr_host
  port: !secret radarr_port
  monitored_conditions:
    - movies
    - upcoming
    - commands
    - status
- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret radarr_host
  port: !secret radarr_port
  days: 120

- platform: sonarr
  api_key: !secret sonarr_api
  host: !secret sonarr_host
  port: !secret sonarr_port
  monitored_conditions:
    - upcoming
    - wanted
    - commands
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret sonarr_host
  port: !secret sonarr_port
  days: 2


# - platform: deluge
#   host: !secret deluge_host
#   username: !secret deluge_user
#   password: !secret deluge_pass
#   monitored_variables:
#     - 'current_status'
#     - 'download_speed'
#     - 'upload_speed'

- platform: cert_expiry
  host: !secret root_domian

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /unraid/mnt/user
    - type: disk_free
      arg: /unraid/mnt/cache
    - type: disk_free
      arg: /unraid/mnt/disk1
    - type: disk_free
      arg: /unraid/mnt/disk2
    - type: disk_free
      arg: /unraid/mnt/disk3
    - type: disk_free
      arg: /unraid/mnt/disk4
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot

# - platform: sunpower
#   username: !secret sunpower_user
#   password: !secret sunpower_pass
#   monitored_conditions:
#     - energyProduction
#     - energyConsumption
#     - powerProduction
#     - powerConsumption
