- platform: template
  sensors:
    solar_raw_lifetime_net_energy:
      friendly_name: 'Lifetime Raw Net Energy'
      unit_of_measurement: 'kWh'
      entity_id:
        - sensor.solar_consumptionmeter_pvs5m644235c
      value_template: >-
        {{state_attr('sensor.solar_consumptionmeter_pvs5m644235c', 'net_ltea_3phsum_kwh')}}
    solar_raw_house_usage:
      friendly_name: 'Raw Current House Power Usage'
      unit_of_measurement: 'kW'
      entity_id:
        - sensor.solar_raw_total_power
        - sensor.solar_consumptionmeter_pvs5m644235c
      value_template: >-
        {% if states('sensor.solar_consumptionmeter_pvs5m644235c') is defined %}
          {{([states('sensor.solar_raw_total_power')|float + states('sensor.solar_consumptionmeter_pvs5m644235c')|float,0]|max)|round(2)}}
        {% endif %}
    solar_daily_house_usage_energy:
      friendly_name: 'Daily useage of energy'
      unit_of_measurement: 'kWh'
      entity_id:
        - sensor.house_daily_net_energy
        - sensor.solar_daily_energy
      value_template: >-
        {{states('sensor.solar_daily_energy')|float + states('sensor.house_daily_net_energy')|float}}

- platform: filter
  name: 'Current Solar Power'
  entity_id: sensor.solar_raw_total_power
  filters:
    - filter: lowpass
      time_constant: 15
      precision: 2
- platform: filter
  name: 'Current House Usage'
  entity_id: sensor.solar_raw_house_usage
  filters:
    - filter: lowpass
      time_constant: 15
      precision: 2
- platform: filter
  name: 'Current Power Export'
  entity_id: sensor.solar_raw_grid_export
  filters:
    - filter: lowpass
      time_constant: 15
      precision: 2
- platform: filter
  name: 'Current House Consumption'
  entity_id: sensor.solar_consumptionmeter_pvs5m644235c
  filters:
    - filter: lowpass
      time_constant: 15
      precision: 2
