- platform: template
  sensors:
    solar_raw_total_power:
      friendly_name: 'Raw Total Solar Power Production'
      unit_of_measurement: 'kW'
      value_template: >-
        {% if states.sensor|selectattr('attributes.DEVICE_TYPE','equalto','Inverter')|list|length == 24 %}
          {{states.sensor|selectattr('attributes.DEVICE_TYPE','equalto','Inverter')|map(attribute='state')|map('float')|sum|round(2)}}
        {% endif %}
    solar_raw_lifetime_net_energy:
      friendly_name: 'Lifetime Raw Net Energy'
      unit_of_measurement: 'kWh'
      value_template: >-
        {{state_attr('sensor.solar_consumptionmeter_pvs5m644235c', 'net_ltea_3phsum_kwh')}}
    solar_raw_house_usage:
      friendly_name: 'Raw Current House Power Usage'
      unit_of_measurement: 'kW'
      value_template: >-
        {% if states.sensor|selectattr('attributes.DEVICE_TYPE','equalto','Inverter')|list|length == 24 and states('sensor.solar_consumptionmeter_pvs5m644235c') is defined %}
          {{([states('sensor.solar_raw_total_power')|float + states('sensor.solar_consumptionmeter_pvs5m644235c')|float,0]|max)|round(2)}}
        {% endif %}
    solar_raw_export:
      friendly_name: 'Raw Exported Power'
      unit_of_measurement: 'kW'
      value_template: >-
        {% if states('sensor.solar_consumptionmeter_pvs5m644235c') is defined %}
          {{ [states('sensor.solar_consumptionmeter_pvs5m644235c')|float * -1, 0]|max|round(2) }} 
        {% endif %}

- platform: filter
  name: 'Current Solar Power'
  entity_id: sensor.solar_raw_total_power
  filters:
    - filter: lowpass
      precision: 2
- platform: filter
  name: 'Current House Usage'
  entity_id: sensor.solar_raw_house_usage
  filters:
    - filter: lowpass
      precision: 2
- platform: filter
  name: 'Current Power Export'
  entity_id: sensor.solar_raw_export
  filters:
    - filter: lowpass
      precision: 2
