- alias: '[TTS] Movie Downloaded'
  trigger:
  - platform: event
    event_type: MOVIE_DOWNLOADED
    event_data: {}
  condition: []
  action:
  - service: tts.google_say
    data_template:
      entity_id: media_player.living_room_speaker
      message: 'Get the popcorn ready, I just downloaded {{ trigger.event.data["title"] }}.'
