- id: '1618360194429'
  alias: Master - Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping
    to: 'on'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: sensor.home_status
    state: Occupied
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - repeat:
      until:
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'
      sequence:
      - service: media_player.play_media
        target:
          entity_id: media_player.master_bedroom_speaker
        data:
          media_content_id: https://storage.googleapis.com/relaxation-sounds/country_night_3600.mp3
          media_content_type: music
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - wait_for_trigger:
        - platform: state
          entity_id: media_player.master_bedroom_speaker
          from: playing
          for: 0:00:10
        - platform: state
          entity_id: input_boolean.sleeping
  - service: media_player.turn_off
    target:
      entity_id: media_player.master_bedroom_speaker
  mode: single
- id: f4442aab-21d6-4ee1-ac21-a3de30bdee0f
  alias: Fireplace - Fan Auto Off
  trigger:
  - platform: state
    entity_id: switch.fireplace_flame
    to: 'off'
    for: 00:05:00
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.fireplace_fan
  mode: single
- id: 80b144d9-d108-4f29-a7cd-01c730e7b8ea
  alias: 'Schedule - Wake Up'
  trigger:
    - platform: time
      at: '07:15:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: script.goodmorning
- id: 775bbb47-3e20-4c6f-bf19-b2c8d232490b
  alias: 'Schedule - Bedtime'
  trigger:
    - platform: time
      at: '01:30:00'
  action:
    - service: script.goodnight
