- id: '1665955128972'
  alias: Weston - Sleep
  description: ''
  use_blueprint:
    path: loop_media.yaml
    input:
      input_boolean: input_boolean.weston_nap
      media_player: media_player.weston_s_room_speaker
      media_url: https://storage.googleapis.com/relaxation-sounds/ocean_3600.mp3
- id: '1665955215413'
  alias: Harrison - Sleep
  description: ''
  use_blueprint:
    path: loop_media.yaml
    input:
      input_boolean: input_boolean.harrison_nap
      media_player: media_player.harrison_s_room_speaker
      media_url: https://storage.googleapis.com/relaxation-sounds/ocean_3600.mp3
- id: '1665956652468'
  alias: Master - Sleeping
  description: ''
  use_blueprint:
    path: loop_media.yaml
    input:
      input_boolean: binary_sensor.master_sleeping
      media_player: media_player.master_bedroom_speaker
      media_url: https://storage.googleapis.com/relaxation-sounds/country_night_3600.mp3
- id: '1665957065931'
  alias: Justin - Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pixel_fold_is_charging
    to: 'on'
  condition:
  - condition: state
    entity_id: person.justin
    state: home
  - condition: time
    before: 04:00:00
    after: '22:00:00'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.justin_sleeping
  mode: single
- id: '1665957139573'
  alias: Shannon - Sleeping
  description: ''
  trigger:
  - type: plugged_in
    platform: device
    device_id: 696fba9349ae3533504d7614e40aa951
    entity_id: f4d3c8a46c49d108b74e7b60efecea28
    domain: binary_sensor
  condition:
  - condition: time
    before: 04:00:00
    after: '22:00:00'
  - condition: state
    entity_id: person.shannon
    state: home
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.shannon_sleeping
  mode: single
- id: '1665957216248'
  alias: Justin - Wakeup
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.pixel_fold_charger_type
    to: none
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.justin_sleeping
  mode: single
- id: '1665960879923'
  alias: Kids - Bedtime
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
  - condition: state
    entity_id: sensor.main_house_status
    state: Occupied
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
      - input_boolean.weston_nap
      - input_boolean.harrison_nap
  - service: light.turn_on
    data:
      transition: 60
      rgb_color:
      - 0
      - 0
      - 255
      brightness_pct: 10
    target:
      entity_id:
      - light.weston_lamp_light
      - light.harrison_lamp_light
  mode: single
- id: '1665960973192'
  alias: Kids - Wakup
  description: ''
  trigger:
  - platform: time
    at: 07:05:00
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.weston_lamp_light
      state: 'on'
    then:
    - service: light.turn_on
      data:
        color_name: green
        brightness_pct: 50
      target:
        entity_id: light.weston_lamp_light
  - if:
    - condition: state
      entity_id: light.harrison_lamp_light
      state: 'on'
    then:
    - service: light.turn_on
      data:
        color_name: green
        brightness_pct: 50
      target:
        entity_id: light.harrison_lamp_light
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.harrison_nap
      - input_boolean.weston_nap
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.weston_lamp_light
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.harrison_lamp_light
  mode: single
- id: '1666045196645'
  alias: Shannon - Wakeup
  description: ''
  trigger:
  - type: not_plugged_in
    platform: device
    device_id: 696fba9349ae3533504d7614e40aa951
    entity_id: f4d3c8a46c49d108b74e7b60efecea28
    domain: binary_sensor
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.shannon_sleeping
  mode: single
- id: '1667264266778'
  alias: Lights - Outdoor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.main_house_status
  - platform: sun
    event: sunset
    offset: 0
  - platform: time
    at: 00:00:30
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.main_house_status
        state: Occupied
        enabled: false
      - condition: sun
        after: sunset
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
          - switch.laundry_relay
          - switch.outdoor_relay
      alias: Home and after sunset
    default:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.laundry_relay
        - switch.outdoor_relay
  mode: restart
- id: '1668621609140'
  alias: House - Thermostat - Temperature
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.main_house_status
    - schedule.thermostat_saver
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - alias: If Heating
    if:
    - condition: state
      entity_id: climate.main_thermostat
      state: heat
    then:
    - choose:
      - conditions:
        - condition: state
          entity_id: sensor.main_house_status
          state: Occupied
        - condition: state
          entity_id: schedule.thermostat_saver
          state: 'off'
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 65
          target:
            entity_id: climate.main_thermostat
      - conditions:
        - condition: state
          entity_id: sensor.main_house_status
          state: Occupied
        - condition: state
          entity_id: schedule.thermostat_saver
          state: 'on'
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 65
          target:
            entity_id: climate.main_thermostat
      default:
      - service: climate.set_temperature
        data:
          temperature: 63
        target:
          entity_id: climate.main_thermostat
  - if:
    - condition: state
      entity_id: climate.main_thermostat
      state: cool
    then:
    - choose:
      - conditions:
        - condition: state
          entity_id: sensor.main_house_status
          state: Empty
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 77
          target:
            entity_id: climate.main_thermostat
      - conditions:
        - condition: state
          entity_id: sensor.main_house_status
          state: Sleeping
        sequence:
        - service: climate.set_temperature
          data:
            temperature: 72
          target:
            entity_id: climate.main_thermostat
      default:
      - service: climate.set_temperature
        data:
          temperature: 73
        target:
          entity_id: climate.main_thermostat
    alias: If Cooling
  mode: restart
- id: '1668958485089'
  alias: NFL - Score
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.buffalo_bills
    attribute: team_score
  condition:
  - condition: state
    entity_id: sensor.main_house_status
    state: Occupied
  - condition: state
    entity_id: sensor.buffalo_bills
    state: IN
  action:
  - service: media_player.play_media
    data:
      media_content_id: media-source://media_source/cache/nfl/shout.mp3
      media_content_type: music
    target:
      entity_id: media_player.kitchen_display
  - repeat:
      until:
      - condition: state
        entity_id: media_player.kitchen_display
        state: idle
        for:
          hours: 0
          minutes: 0
          seconds: 5
      sequence:
      - service: light.turn_on
        data:
          color_name: blue
          brightness_pct: 100
        target:
          entity_id: light.living_room_lamp_light
        alias: Set Light Red
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: light.turn_on
        data:
          color_name: red
          brightness_pct: 100
        target:
          entity_id: light.living_room_lamp_light
        alias: Set Light Blue
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
    alias: Blink Red - Blue Until Music Stops
    enabled: false
  - wait_for_trigger:
    - platform: state
      entity_id:
      - media_player.kitchen_display
      from: playing
      to: idle
      for:
        hours: 0
        minutes: 0
        seconds: 5
  - service: automation.trigger
    data: {}
    target:
      entity_id: automation.living_room_lights
  mode: single
- id: '1670163832317'
  alias: NFL - Kickoff
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.buffalo_bills
    from: PRE
    to: IN
  condition:
  - condition: state
    entity_id: sensor.main_house_status
    state: Occupied
  action:
  - service: media_player.play_media
    data:
      media_content_id: media-source://media_source/cache/nfl/theme.mp3
      media_content_type: music
    target:
      entity_id: media_player.kitchen_display
  mode: single
- id: '1670164027027'
  alias: Fire - New Job
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bryx_open_job
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: person.justin
    state: home
  action:
  - service: tts.google_translate_say
    data:
      entity_id:
      - media_player.kitchen_display
      - media_player.office_speaker
      - media_player.master_bedroom_speaker
      cache: false
      message: 'Alert: {{ states(''sensor.bryx_current_job_type'') }} {{ states(''sensor.bryx_current_job_synopsis'')
        }} at {{ states(''sensor.bryx_current_job_address'') }}'
  - delay:
      seconds: 15
  - service: media_player.play_media
    data:
      entity_id:
      - media_player.office_speaker
      - media_player.kitchen_display
      media_content_id: '{{states(''sensor.wcf_scanner_stream'')}}'
      media_content_type: music
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.bryx_open_job
      from: 'on'
      to: 'off'
      for: 0:05:00
    - platform: state
      entity_id:
      - person.justin
      from: home
    timeout:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: media_player.media_stop
    data:
      entity_id:
      - media_player.office_speaker
      - media_player.kitchen_display
  mode: single
- id: '1670633918685'
  alias: 'Master - Light '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.master_sleeping
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.master_lamp_switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.master_lamp_switch
  mode: single
- id: '1671768815389'
  alias: ZHA - Status
  description: ''
  trigger:
  - device_id: d8949c59ee747cceaf416afd3b82e8c4
    domain: zha
    platform: device
    type: device_offline
    subtype: device_offline
  condition: []
  action:
  - service: notify.mobile_app_pixel_fold
    data:
      title: Device Offline!
      message: The thermostat is offline!
  mode: single
- id: '1678416614805'
  alias: 'Watch - Charged '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.google_pixel_watch_battery_state
    from: charging
    to: full
  condition: []
  action:
  - service: notify.mobile_app_pixel_fold
    data:
      title: Pixel Watch Charged
      message: Put your watch back on.
  mode: single
- id: '1681821203093'
  alias: Overall - Dark Outside
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 21
  - platform: numeric_state
    entity_id: sun.sun
    below: 19
    attribute: elevation
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 20
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.dark_outside
    default:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.dark_outside
  mode: single
- id: '1691088773736'
  alias: House - Thermostat - Fan
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.main_thermostat
    attribute: hvac_action
    from: cooling
    to: fan
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - platform: state
    entity_id:
    - climate.main_thermostat
    attribute: hvac_action
    to: cooling
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: climate.main_thermostat
        attribute: hvac_action
        state: fan
        for:
          hours: 0
          minutes: 20
          seconds: 0
      sequence:
      - service: climate.set_fan_mode
        data:
          fan_mode: auto
        target:
          entity_id: climate.main_thermostat
      - service: notify.mobile_app_pixel_fold
        data:
          message: Turning A/C Fan to Auto
          title: A/C Change
    - conditions:
      - condition: state
        entity_id: climate.main_thermostat
        attribute: hvac_action
        state: cooling
        for:
          hours: 0
          minutes: 2
          seconds: 0
      sequence:
      - service: climate.set_fan_mode
        data:
          fan_mode: 'on'
        target:
          entity_id: climate.main_thermostat
      - service: notify.mobile_app_pixel_fold
        data:
          message: Turning A/C Fan On
          title: A/C Change
  mode: restart
- id: '1693661948520'
  alias: Garage - Power Out
  description: ''
  trigger:
  - type: not_connected
    platform: device
    device_id: 3217afc6ee177c4d88975ed4383ac764
    entity_id: c63fe67db61a9bc6540af015e3a30991
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - service: notify.mobile_app_pixel_fold
    data:
      title: Garage Power Out
      message: The power in the garage is currently out and the garage fridge is not
        running!!!
  mode: single
- id: '1696297872437'
  alias: Kids - Bus Reminder
  description: ''
  trigger:
  - platform: time
    at: '15:55:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: sensor.main_house_status
    state: Occupied
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.first_floor
    data:
      media_content_id: media-source://tts/google_translate?message=Time+to+get+Weston+off+the+bus%21&language=en-us
      media_content_type: provider
    metadata:
      title: Time to get Weston off the bus!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Time+to+get+Weston+off+the+bus%21&language=en-us
  mode: single
- id: '1700511612566'
  alias: Lights - Indoor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.main_house_status
  - platform: state
    entity_id:
    - input_boolean.dark_outside
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.dark_outside
        state: 'on'
      - condition: state
        entity_id: sensor.main_house_status
        state: Occupied
      sequence:
      - service: light.turn_on
        data:
          transition: 20
          brightness_pct: 30
        target:
          entity_id:
          - light.kitchen_can_lights
          - light.kitchen_pendant_lights
          - light.living_room_cans_light
      - service: light.turn_on
        data:
          kelvin: 2800
          transition: 20
        target:
          entity_id: light.office_lamp
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
          - switch.entryway_outlet_switch
          - switch.living_room_outlet_switch_bottom
      alias: Dark and Home
    - conditions:
      - condition: or
        conditions:
        - condition: not
          conditions:
          - condition: state
            entity_id: sensor.main_house_status
            state: Occupied
          alias: House is not Occupied
        - condition: state
          entity_id: input_boolean.dark_outside
          state: 'off'
      sequence:
      - service: retry.actions
        continue_on_error: true
        metadata: {}
        data:
          sequence:
          - service: homeassistant.turn_off
            data: {}
            target:
              entity_id:
              - switch.living_room_outlet_switch_bottom
              - switch.entryway_outlet_switch
      - service: retry.actions
        continue_on_error: true
        metadata: {}
        data:
          sequence:
          - service: light.turn_off
            metadata: {}
            data:
              transition: 20
            target:
              entity_id:
              - light.office_lamp
              - light.kitchen_can_lights
              - light.kitchen_pendant_lights
              - light.living_room_cans_light
          state_grace: 22
      alias: Not Home Or Not Dark
  mode: restart
