person.justin:
  entity_picture: /local/avatars/Justin.jpg
person.shannon:
  entity_picture: /local/avatars/Shannon.jpg
device_tracker.bolt_2:
  entity_picture: /local/avatars/Bolt.jpg
device_tracker.tellulah_location:
  entity_picture: /local/avatars/Tellulah.jpg
sensor.furnace_home_energy_usage:
  device_class: energy
