- id: '1609092467123'
  name: Kitchen - Default
  entities:
    light.kitchen_down:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      brightness: 183
      hs_color:
      - 60
      - 43.137
      rgb_color:
      - 255
      - 255
      - 145
      xy_color:
      - 0.396
      - 0.443
      effect: None
      friendly_name: Kitchen Down
      supported_features: 61
      state: 'on'
    light.kitchen_up:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      brightness: 183
      hs_color:
      - 60
      - 43.137
      rgb_color:
      - 255
      - 255
      - 145
      xy_color:
      - 0.396
      - 0.443
      effect: None
      friendly_name: Kitchen Up
      supported_features: 61
      state: 'on'
- id: '1609092905200'
  name: Kitchen - Fire Call
  entities:
    light.kitchen_down:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      brightness: 255
      hs_color:
      - 0
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      effect: None
      friendly_name: Kitchen Down
      supported_features: 61
      state: 'on'
    light.kitchen_up:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      brightness: 255
      hs_color:
      - 0
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      effect: None
      friendly_name: Kitchen Up
      supported_features: 61
      state: 'on'
- id: '1609092980394'
  name: Kitchen - Dim
  entities:
    light.kitchen_down:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      brightness: 64
      hs_color:
      - 60
      - 43.137
      rgb_color:
      - 255
      - 255
      - 145
      xy_color:
      - 0.396
      - 0.443
      effect: None
      friendly_name: Kitchen Down
      supported_features: 61
      state: 'on'
    light.kitchen_up:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      brightness: 64
      hs_color:
      - 60
      - 43.137
      rgb_color:
      - 255
      - 255
      - 145
      xy_color:
      - 0.396
      - 0.443
      effect: None
      friendly_name: Kitchen Up
      supported_features: 61
      state: 'on'
- id: '1609094404807'
  name: Kitchen - Off
  entities:
    light.kitchen_down:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      friendly_name: Kitchen Down
      supported_features: 61
      state: 'off'
    light.kitchen_up:
      effect_list:
      - None
      - Slow Random Colors
      - Fast Random Colors
      - In Alarm
      - Strobe - Rainbow
      friendly_name: Kitchen Up
      supported_features: 61
      state: 'off'
- id: '1609167557463'
  name: Office - Off
  entities:
    light.office_lamp:
      min_mireds: 153
      max_mireds: 666
      effect_list:
      - colorloop
      off_brightness:
      friendly_name: Office Lamp
      supported_features: 63
      state: 'off'
    zwave.office_outlet:
      node_id: 4
      node_name: Office Outlet
      manufacturer_name: 'Unknown: id=0063'
      product_name: 'Unknown: type=4952, id=3133'
      query_stage: Complete
      is_awake: true
      is_ready: true
      is_failed: false
      is_info_received: true
      max_baud_rate: 40000
      is_zwave_plus: true
      capabilities:
      - zwave_plus
      - beaming
      - routing
      - listening
      neighbors:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 9
      sentCnt: 24
      sentFailed: 0
      retries: 0
      receivedCnt: 13
      receivedDups: 0
      receivedUnsolicited: 0
      sentTS: '2020-12-28 09:59:11:867 '
      receivedTS: '2020-12-28 09:59:11:902 '
      lastRequestRTT: 23
      averageRequestRTT: 23
      lastResponseRTT: 34
      averageResponseRTT: 34
      application_version: '5.23'
      friendly_name: Office Outlet
      state: ready
    switch.office_outlet:
      node_id: 4
      value_index: 0
      value_instance: 1
      value_id: '72057594109837312'
      friendly_name: Office Outlet Switch
      state: 'off'
- id: '1609167585968'
  name: Office - Default
  entities:
    light.office_lamp:
      min_mireds: 153
      max_mireds: 666
      effect_list:
      - colorloop
      brightness: 176
      color_temp: 666
      hs_color:
      - 195
      - 85.714
      rgb_color:
      - 36
      - 200
      - 255
      xy_color:
      - 0.152
      - 0.254
      off_brightness:
      friendly_name: Office Lamp
      supported_features: 63
      state: 'on'
    zwave.office_outlet:
      node_id: 4
      node_name: Office Outlet
      manufacturer_name: 'Unknown: id=0063'
      product_name: 'Unknown: type=4952, id=3133'
      query_stage: Complete
      is_awake: true
      is_ready: true
      is_failed: false
      is_info_received: true
      max_baud_rate: 40000
      is_zwave_plus: true
      capabilities:
      - zwave_plus
      - beaming
      - routing
      - listening
      neighbors:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 9
      sentCnt: 26
      sentFailed: 0
      retries: 0
      receivedCnt: 14
      receivedDups: 0
      receivedUnsolicited: 0
      sentTS: '2020-12-28 09:59:43:958 '
      receivedTS: '2020-12-28 09:59:43:993 '
      lastRequestRTT: 23
      averageRequestRTT: 23
      lastResponseRTT: 35
      averageResponseRTT: 34
      application_version: '5.23'
      friendly_name: Office Outlet
      state: ready
    switch.office_outlet:
      node_id: 4
      value_index: 0
      value_instance: 1
      value_id: '72057594109837312'
      friendly_name: Office Outlet Switch
      state: 'on'
- id: '1609168156535'
  name: Office - Fire Call
  entities:
    light.office_lamp:
      min_mireds: 153
      max_mireds: 666
      effect_list:
      - colorloop
      brightness: 176
      color_temp: 666
      hs_color:
      - 360
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      off_brightness:
      friendly_name: Office Lamp
      supported_features: 63
      state: 'on'
    zwave.office_outlet:
      node_id: 4
      node_name: Office Outlet
      manufacturer_name: 'Unknown: id=0063'
      product_name: 'Unknown: type=4952, id=3133'
      query_stage: Complete
      is_awake: true
      is_ready: true
      is_failed: false
      is_info_received: true
      max_baud_rate: 40000
      is_zwave_plus: true
      capabilities:
      - zwave_plus
      - beaming
      - routing
      - listening
      neighbors:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 9
      sentCnt: 26
      sentFailed: 0
      retries: 0
      receivedCnt: 14
      receivedDups: 0
      receivedUnsolicited: 0
      sentTS: '2020-12-28 09:59:43:958 '
      receivedTS: '2020-12-28 09:59:43:993 '
      lastRequestRTT: 23
      averageRequestRTT: 23
      lastResponseRTT: 35
      averageResponseRTT: 34
      application_version: '5.23'
      friendly_name: Office Outlet
      state: ready
    switch.office_outlet:
      node_id: 4
      value_index: 0
      value_instance: 1
      value_id: '72057594109837312'
      friendly_name: Office Outlet Switch
      state: 'on'
