goodmorning:
  alias: Goodmorning
  sequence:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.justin_sleeping
      - input_boolean.shannon_sleeping
  mode: single
goodnight:
  alias: Goodnight
  sequence:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
      - input_boolean.justin_sleeping
      - input_boolean.shannon_sleeping
  mode: single
