goodmorning:
  alias: Goodmorning
  sequence:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.justin_sleeping
      - input_boolean.shannon_sleeping
  mode: single
goodnight:
  alias: Goodnight
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.shannon
        state: home
      sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.shannon_sleeping
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: person.shannon
        state: home
      sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.shannon_sleeping
    default: []
  mode: single
