goodmorning:
  alias: Goodmorning
  sequence:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sleeping
  mode: single
goodnight:
  alias: Goodnight
  sequence:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sleeping
  mode: single
