title: Misty Way
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/solar.yaml
  - !include lovelace/views/floor-one.yaml
  - !include lovelace/views/floor-two.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/weather.yaml
  - !include lovelace/views/finance.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/settings.yaml
