resources:
  - type: module
    url: /community_plugin/power-wheel-card/power-wheel-card.js
  - type: module
    url: /community_plugin/pc-card/pc-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/roku-card/roku-card.js
  - type: module
    url: /community_plugin/atomic_calendar/atomic_calendar.js
  - type: js
    url: /community_plugin/button-entity-row/button-entity-row.js
  - type: js
    url: /community_plugin/monster-card/monster-card.js
  - type: js
    url: /community_plugin/upcoming-media-card/upcoming-media-card.js
  - type: js
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: js
    url: /community_plugin/lovelace-more-info-card/more-info-card.js
  - type: js
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: js
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: js
    url: /community_plugin/simple-thermostat/simple-thermostat.js
  - type: js
    url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js

title: Misty Way
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/solar.yaml
  - !include lovelace/views/floor-one.yaml
  - !include lovelace/views/floor-two.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/weather.yaml
  - !include lovelace/views/finance.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/settings.yaml
