- alias: '[TTS + Notification] AC Frozen'
  trigger:
    platform: state
    entity_id: sensor.family_room_thermostat_hvac_state
    from: 'off'
    to: 'cooling'
    for:
      hours: 4
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.living_room_speaker
        message: 'Just a heads up, I think the AC might be frozen.'
    - service: notify.web
      data:
        title: 'Possible AC Issue'
        message: 'The AC has been running for 2 hours non stop.'
