- alias: House Became Unoccupied
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
  action:
    - service: script.livingroom_off
    - service: script.kitchen_off
    - service: climate.set_away_mode
      data:
        entity_id: all
        away_mode: true

- alias: House Became Occupied
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Occupied'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: all
        away_mode: false

    # It's dark, we want lights?
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-1:15:00'
        - condition: sun
          before: sunrise
    - service: script.kitchen_on
    - service: script.livingroom_on
