- alias: House Became Unoccupied
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:  
        minutes: 5
  action:
    - service: script.livingroom_off
    - service: script.kitchen_off
    - service: nest.set_away_mode
      data:
        away_mode: away
    - service: fan.turn_off
      data:
        entity_id:
          - fan.master_fan
          - fan.weston_fan

- alias: House Became Occupied
  initial_state: 'on' # Don't want to run every time we reboot and are home.
  trigger:
    - platform: state
      entity_id: sensor.home_status
      from: 'Unoccupied'
      to: 'Occupied'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home

    # It's dark, we want lights?
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-1:15:00'
        - condition: sun
          before: sunrise
    - service: script.kitchen_on
    - service: script.livingroom_on
