- alias: 'Weston Sleep'
  initial_state: 'on'
  trigger:
    # Start times
    - platform: time
      at: '11:45:00'
    - platform: time
      at: '19:45:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.weston_nap

- alias: 'Weston Keep Sleeping'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.weston_nap
      to: 'on'
    # Stopped playing for random reason
    - platform: state
      entity_id: media_player.westons_room_speaker
      to: 'off'
      for: '00:00:10'
    - platform: state
      entity_id: media_player.westons_room_speaker
      to: 'idle'
      for: '00:00:10'
    - platform: state
      entity_id: media_player.westons_room_speaker
      to: 'paused'
      for: '00:00:10'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
    - condition: state
      entity_id: input_boolean.weston_nap
      state: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.westons_room_speaker
        media_content_id: !secret babbling_brook_mp3
        media_content_type: 'music'

- alias: 'Weston Wakup'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.weston_nap
      to: 'off'
    - platform: time
      at: '16:00:00'
    - platform: time
      at: '08:30:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weston_nap
    - service: media_player.turn_off
      data:
        entity_id: media_player.westons_room_speaker
