- alias: '[TTS] Movie Downloaded'
  trigger:
  - platform: event
    event_type: MOVIE_DOWNLOADED
    event_data: {}
  condition:
    condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
  - service: tts.google_say
    entity_id: media_player.living_room_speaker
    data_template:
      message: 'Get the popcorn ready, I just downloaded {{ trigger.event.data["title"] }}.'
