- alias: '[TTS] New TV Episode'
  trigger:
  - platform: event
    event_type: TV_EPISODE_DOWNLOADED
    event_data: {}
  condition:
    condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
  - service: tts.google_say
    entity_id: media_player.living_room_speaker
    data_template:
      message: 'Good news, I downloaded a new episode of {{ trigger.event.data["title"] }} from season {{ trigger.event.data["season"] }} that aired on {{ trigger.event.data["airdate"] }}.'
