- alias: 'Sun - Morning Routine'
  trigger:
    - platform: time
      at: '06:15:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: script.kitchen_on
    - service: script.livingroom_on

- alias: 'Sun - Sunrise Routine'
  trigger:
    - platform: sun
      event: sunrise
      offset: '+1:30:00'
  action:
    - service: script.kitchen_off
    - service: script.livingroom_off
    - service: script.outside_off

- alias: 'Sun - Sunset Routine'
  trigger:
    - platform: sun
      event: sunset
      offset: '-1:15:00'
  action:
    - service: script.outside_on
    ## Only continue if occupied
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'

    - service: script.kitchen_on
    - service: script.livingroom_on

- alias: 'Sun - Bedtime Routine'
  trigger:
    - platform: time
      at: '01:30:00'
  action:
    - service: script.goodnight
