- alias: 'Weston Sleep'
  trigger:
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '19:00:00'
  condition:
    - condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.westons_room_speaker
        media_content_id: !secret babbling_brook_mp3
        media_content_type: 'music'
