title: Cameras
path: cameras
icon: 'mdi:cctv'
badges: []
cards:
  - type: picture-entity
    entity: camera.weston_s_room
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.harrison_s_room
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.living_room
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.garage
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.driveway
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.front_door
    show_name: false
    show_state: false
  - type: entities
    title: Motion Detection
    state_color: true
    entities:
      - switch.camera_living_motion_detection
      - switch.camera_garage_motion_detection
      - switch.camera_driveway_motion_detection
      - switch.camera_front_door_motion_detection
