title: Cameras
path: cameras
icon: 'mdi:cctv'
badges: []
cards:
  - type: picture-entity
    entity: camera.weston_s_room
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.harrison_s_room
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.living_room
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.garage
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.driveway
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.front_door
    show_name: false
    show_state: false
