title: First Floor
icon: 'mdi:home-floor-1'
badges: []
popup_cards:
  media_player.living_room_tv: &roku_remote
    title: Remote
    large: false
    card:
      type: 'custom:roku-card'
      entity: media_player.living_room_tv
      tv: true
cards:
  - title: Lights
    type: entities
    show_header_toggle: false
    entities:
      - type: 'custom:slider-entity-row'
        toggle: true
        entity: light.kitchen_up

      - type: 'custom:slider-entity-row'
        toggle: true
        entity: light.kitchen_down

      - switch.living_room_outlet_corner
      - switch.living_room_outlet_stairs
      - switch.office_outlet

  - type: custom:mini-media-player
    entity: media_player.kitchen_display

  - type: custom:mini-media-player
    entity: media_player.office_speaker

  - type: custom:mini-media-player
    title: Living Room TV
    entity: media_player.living_room_tv
    volume_stateless: true
    shortcuts:
      buttons:
        - icon: mdi:remote-tv
          type: service
          id: browser_mod.popup
          data: 
            <<: *roku_remote

  - title: Deebot
    type: 'custom:more-info-card'
    entity: vacuum.deebot

  - type: picture-entity
    entity: camera.living_room
    show_name: false
    show_state: false
