title: Second Floor
path: floor-two
icon: 'mdi:home-floor-2'
badges: []
# This is so the CSS isn't forcing everything into a single column
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - title: Westons's Room
        type: picture-entity
        entity: camera.weston_s_room
        show_name: false
        show_state: false

      - title: Weston's Room
        type: entities
        show_header_toggle: false
        entities:
          - type: 'custom:slider-entity-row'
            entity: fan.weston_fan
            hide_when_off: true
            toggle: true
          - entity: input_boolean.weston_nap
          - entity: sensor.weston_relative_humidity
          - entity: sensor.weston_luminance

      - title: Weston's Room Temp
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 24
        points_per_hour: 2
        show:
          labels: true
        entities:
          - sensor.weston_temperature

      - type: custom:mini-media-player
        entity: media_player.westons_room_speaker

      - break

      - title: Harrison's Room
        type: picture-entity
        entity: camera.harrison_s_room
        show_name: false
        show_state: false

      - title: Harrison's Room
        type: entities
        show_header_toggle: false
        entities:
          - type: 'custom:slider-entity-row'
            entity: fan.harrison_fan
            hide_when_off: true
            toggle: true
          - entity: input_boolean.harrison_nap
          - entity: sensor.harrison_relative_humidity
          - entity: sensor.harrison_luminance

      - title: Harrison's Room Temp
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 24
        points_per_hour: 2
        show:
          labels: true
        entities:
          - sensor.harrison_temperature

      - type: custom:mini-media-player
        entity: media_player.harrisons_room_speaker

      - break

      - type: custom:mini-media-player
        title: Living Room TV
        entity: media_player.lg_tv_remote
        volume_stateless: true
        hide:
          controls: true
          source: true

      - title: Master Bedroom
        type: entities
        show_header_toggle: false
        entities:
          - type: 'custom:slider-entity-row'
            entity: fan.master_fan
            hide_when_off: true
            toggle: true

      - type: custom:mini-media-player
        entity: media_player.master_bedroom_speaker
