title: First Floor
path: floor-one
icon: 'mdi:home-floor-1'
badges: []
popup_cards:
  media_player.living_room_tv: &roku_remote
    title: Remote
    large: false
    card:
      type: 'custom:roku-card'
      entity: media_player.living_room_tv
      tv: true
cards:
  - title: Lights
    type: entities
    show_header_toggle: false
    state_color: true
    entities:
      - type: 'custom:slider-entity-row'
        toggle: true
        entity: light.kitchen_up

      - type: 'custom:slider-entity-row'
        toggle: true
        entity: light.kitchen_down

      - switch.living_room_corner
      - switch.living_room_stairs
      - switch.office_outlet

  - type: custom:mini-media-player
    entity: media_player.kitchen_display

  - type: custom:mini-media-player
    entity: media_player.office_speaker
  - title: Office
    type: entities
    entities:
      - sensor.office_temperature
      - sensor.office_relative_humidity


  - type: entities
    entities:
      - type: custom:mini-media-player
        title: Living Room TV
        entity: media_player.living_room_tv
        volume_stateless: true
      - type: custom:fold-entity-row
        head:
          type: section
          label: Remote
        entities:
          - type: 'custom:roku-card'
            entity: media_player.living_room_tv
            tv: true

  - type: picture-entity
    entity: camera.living_room
    show_name: false
    show_state: false
