title: Home
path: home
icon: 'mdi:home-assistant'
badges: []
# This is so the CSS isn't forcing everything into a single column
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: 'custom:simple-thermostat'
        entity: climate.family_room
        decimals: 0
        step_size: 1
        hide:
          state: true
        sensors:
          - entity: sensor.family_room_thermostat_humidity
            name: Humidity
          - entity: sensor.family_room_thermostat_hvac_state
            name: State
          - entity: binary_sensor.family_room_thermostat_fan
            name: Fan

      - title: Family Room Temperature
        type: 'custom:mini-graph-card'
        hour24: true
        extrema: true
        hours_to_show: 24
        points_per_hour: 2
        entities:
          - sensor.family_room_thermostat_temperature
          - sensor.office_temperature
          - sensor.weston_temperature
          - sensor.harrison_temperature
          - sensor.master_temperature_zigbee

      - break

      - title: People
        type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.home_status
          - type: 'custom:auto-entities'
            card:
              type: 'custom:fold-entity-row'
              head: person.justin
            entities:
              - type: call-service
                name: Update Location
                action_name: Send
                service: notify.mobile_app_pixel_2
                service_data:
                  message: request_location_update
            filter:
              include:
                - device: Pixel 2
          - type: 'custom:auto-entities'
            card:
              type: 'custom:fold-entity-row'
              head: person.shannon
            entities:
              - type: call-service
                name: Update Location
                action_name: Send
                service: notify.mobile_app_pixel_3a_xl
                service_data:
                  message: request_location_update
            filter:
              include:
                - device: Pixel 3a XL
          - entity: input_boolean.guest_mode

      - type: map
        # aspect_ratio: '16:9'
        default_zoom: 14
        dark_mode: true
        hours_to_show: 24
        entities:
          - zone.home
          - zone.ofd_station_1
          - zone.ofd_station_2
          - zone.ofd_station_3
          - zone.paychex_basket
          - zone.rgh
          - zone.urgent_care_now
          - person.justin
          - person.shannon
          - device_tracker.bolt

      - break
      
      - title: Outside
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - cover.garage_door_opener
          - switch.porch_light
          - switch.driveway_light
          - light.garage_leds
          - light.porch_leds

      - title: Bolt
        type: entities
        show_header_toggle: false
        entities:
          - type: 'custom:mini-graph-card'
            hour24: true
            hours_to_show: 4
            points_per_hour: 12
            lower_bound: 0
            upper_bound: 100
            align_icon: left
            align_state: center
            color_thresholds:
              - value: 100
                color: green
              - value: 50
                color: yellow
              - value: 0
                color: red
            show:
              labels: true
            entities:
              - sensor.bolt_soc
          - binary_sensor.bolt_charging
          - sensor.bolt_battery_temp
