title: Home
icon: 'mdi:home-assistant'
badges: []
# This is so the CSS isn't forcing everything into a single column
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    max_columns: 3
    cards:
      - type: 'custom:simple-thermostat'
        entity: climate.family_room
        decimals: 0
        step_size: 1
        hide:
          state: true
        sensors:
          - entity: sensor.family_room_thermostat_hvac_state
            name: State
          - entity: binary_sensor.family_room_thermostat_fan
            name: Fan

      - title: Family Room Temperature
        type: 'custom:mini-graph-card'
        hour24: true
        extrema: true
        hours_to_show: 24
        points_per_hour: 2
        entities:
          - sensor.family_room_thermostat_temperature
          - sensor.weston_temperature
          - sensor.harrison_temperature

      - break

      - title: Locations
        type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.home_status
          - entity: person.justin
          - entity: person.shannon
          - entity: input_boolean.guest_mode
      - type: map
        # aspect_ratio: '16:9'
        default_zoom: 14
        dark_mode: true
        entities:
          - zone.home
          - person.justin
          - person.shannon
          

      - break
      
      - title: Outside
        type: entities
        show_header_toggle: false
        entities:
          - cover.garage_door_opener
          - switch.porch_light
          - switch.driveway_light
          - light.garage_leds
          - light.porch_leds
          - switch.skybell_front_door_motion_sensor
      
      - title: Chevy Bolt
        type: entities
        show_header_toggle: false
        entities:
          - binary_sensor.mychevy_2017_chevrolet_bolt_ev_plugged_in
          - sensor.mychevy_2017_chevrolet_bolt_ev_battery_level
          - sensor.mychevy_2017_chevrolet_bolt_ev_charge_mode
          - sensor.mychevy_2017_chevrolet_bolt_ev_charged_by
          - sensor.mychevy_2017_chevrolet_bolt_ev_electric_range
          - sensor.mychevy_2017_chevrolet_bolt_ev_mileage
          - sensor.mychevy_status
