title: Media
path: media
icon: 'mdi:television-box'
badges: []
cards:
  - title: Plex
    type: entities
    show_header_toggle: false
    entities:
      - sensor.plex
  
  - type: custom:upcoming-media-card
    entity: sensor.plex_recently_added
    title: Recently Downloaded

  - title: Movies
    type: entities
    show_header_toggle: false
    entities:
      - sensor.radarr_upcoming
      - sensor.radarr_movies
      - sensor.radarr_status
    
  - title: TV Shows
    type: entities
    show_header_toggle: false
    entities:
      - sensor.sonarr_upcoming
      - sensor.sonarr_wanted

  - title: Upcoming TV
    type: 'custom:upcoming-media-card'
    entity: sensor.sonarr_upcoming_media

  - title: Upcoming Movies
    type: 'custom:upcoming-media-card'
    entity: sensor.radarr_upcoming_media
