title: Settings
icon: 'mdi:settings'
badges: []
cards:
  - type: horizontal-stack
    cards:
      - title: Download
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 48
        points_per_hour: 0.25
        entities:
          - entity: sensor.speedtest_download
            name: Download

      - title: Upload
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 48
        points_per_hour: 0.25
        entities:
          - entity: sensor.speedtest_upload
            name: Upload

      - title: Ping
        type: 'custom:mini-graph-card'
        extrema: true
        hours_to_show: 48
        points_per_hour: 0.25
        entities:
          - entity: sensor.speedtest_ping
            name: Ping

  - title: Certificates
    type: entities
    show_header_toggle: false
    entities:
      - sensor.home_assistant_cert_expiration
      - sensor.auth_cert_expiration
      - sensor.code_cert_expiration
      - sensor.tv_cert_expiration
      - sensor.movies_cert_expiration
      - sensor.plex_cert_expiration
      - sensor.grafana_cert_expiration
      - sensor.security_cert_expiration
      - sensor.unraid_cert_expiration
      - sensor.pfsense_cert_expiration
      - sensor.music_cert_expiration
      - sensor.sync_cert_expiration
      - sensor.hydra_cert_expiration
      - sensor.usenet_cert_expiration
    
  - title: Unraid
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.processor_use
      - entity: sensor.memory_use_percent
      - entity: sensor.disk_free_unraid_mnt_user
      - entity: sensor.disk_free_unraid_mnt_cache
      - entity: sensor.disk_free_unraid_mnt_disk1
      - entity: sensor.disk_free_unraid_mnt_disk2
      - entity: sensor.disk_free_unraid_mnt_disk3
      - entity: sensor.disk_free_unraid_mnt_disk4
      - entity: sensor.last_boot

  - title: HACS
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.hacs

  - title: Sabnzbd
    type: entities
    show_header_toggle: false
    entities:
      - sensor.sabnzbd_status
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_queue_count
      - sensor.sabnzbd_queue
      - sensor.sabnzbd_left
      - sensor.sabnzbd_disk
      - sensor.sabnzbd_disk_free
    
  - title: Devices
    type: entities
    show_header_toggle: false
    entities:
      - entity: binary_sensor.family_room_thermostat_online
      - entity: switch.gaming_pc

  - type: 'custom:monster-card'
    card:
      title: Z-Wave
      type: glance
    filter:
      include:
        - domain: zwave
  - type: 'custom:monster-card'
    card:
      title: Automations
      type: entities
    filter:
      include:
        - domain: automation
  
  - type: entities
    title: Phones
    show_header_toggle: false
    entities:
      - entity: sensor.pixel_2_battery_level
      - entity: sensor.pixel_2_wifi_connection
      - entity: sensor.pixel_3a_xl_battery_level
      - entity: sensor.pixel_3a_xl_wifi_connection
