title: Settings
path: settings
icon: 'mdi:cog'
badges: []
visible:
  - user: !secret userid_justin
cards:
  - title: Network Speed
    type: entities
    show_header_toggle: false
    entities:
      - type: button
        name: Start Test
        tap_action:
          action: call-service
          service: speedtestdotnet.speedtest
      - type: custom:fold-entity-row
        head: sensor.speedtest_download
        entities:
          - type: 'custom:mini-graph-card'
            hours_to_show: 168
            points_per_hour: 0.25
            entities:
              - entity: sensor.speedtest_download
            show:
              name: false
              icon: false
              state: false
              average: true
              extrema: true

      - type: custom:fold-entity-row
        head: sensor.speedtest_upload
        entities:
          - type: 'custom:mini-graph-card'
            hours_to_show: 168
            points_per_hour: 0.25
            entities:
              - entity: sensor.speedtest_upload
            show:
              name: false
              icon: false
              state: false
              average: true
              extrema: true

      - type: custom:fold-entity-row
        head: sensor.speedtest_ping
        entities:
          - type: 'custom:mini-graph-card'
            hours_to_show: 168
            points_per_hour: 0.25
            entities:
              - entity: sensor.speedtest_ping
            show:
              name: false
              icon: false
              state: false
              average: true
              extrema: true

  - title: SpaceX
    type: entities
    show_header_toggle: false
    entities:
      - sensor.next_launch_mission
      - sensor.next_launch_day
      - sensor.next_launch_time
      - sensor.next_launch_site
      - sensor.next_launch_rocket

  - title: Certificates
    type: entities
    show_header_toggle: false
    entities:
      - sensor.cert_expiry_timestamp_ssvnormandy_com
    
  - title: Unraid
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.processor_use
      - entity: sensor.memory_use_percent
      - entity: sensor.disk_free_unraid_mnt_user
      - entity: sensor.disk_free_unraid_mnt_cache
      - entity: sensor.disk_free_unraid_mnt_disk1
      - entity: sensor.disk_free_unraid_mnt_disk2
      - entity: sensor.disk_free_unraid_mnt_disk3
      - entity: sensor.disk_free_unraid_mnt_disk4
      - entity: sensor.last_boot

  - title: HACS
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.hacs

  - title: Sabnzbd
    type: entities
    show_header_toggle: false
    entities:
      - sensor.sabnzbd_status
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_queue_count
      - sensor.sabnzbd_queue
      - sensor.sabnzbd_left
      - sensor.sabnzbd_disk
      - sensor.sabnzbd_disk_free
    
  - title: Devices
    type: entities
    show_header_toggle: false
    entities:
      - entity: binary_sensor.family_room_thermostat_online
      - entity: switch.gaming_pc

  - type: entities
    title: Z-Wave
    show_header_toggle: false
    entities:
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Details
        filter:
          include:
            - domain: zwave
        sort:
          method: name

  - title: Automations
    type: entities
    show_header_toggle: false
    entities:
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Almost Home
        filter:
          include:
            - domain: automation
              name: 'Almost Home - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Bolt
        filter:
          include:
            - domain: automation
              name: 'Bolt - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Cameras
        filter:
          include:
            - domain: automation
              name: 'Cameras - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Furnace
        filter:
          include:
            - domain: automation
              name: 'Furnace - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Garage Door
        filter:
          include:
            - domain: automation
              name: 'Garage Door - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Harrison
        filter:
          include:
            - domain: automation
              name: 'Harrison - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Kitchen
        filter:
          include:
            - domain: automation
              name: 'Kitchen - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Lifecycles
        filter:
          include:
            - domain: automation
              name: 'Lifecycles - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Livingroom
        filter:
          include:
            - domain: automation
              name: 'Livingroom - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Maintenance
        filter:
          include:
            - domain: automation
              name: 'Maintenance - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Master
        filter:
          include:
            - domain: automation
              name: 'Master - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Outside
        filter:
          include:
            - domain: automation
              name: 'Outside - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Plex
        filter:
          include:
            - domain: automation
              name: 'Plex - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Solar
        filter:
          include:
            - domain: automation
              name: 'Solar - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: SpaceX
        filter:
          include:
            - domain: automation
              name: 'SpaceX - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Theater
        filter:
          include:
            - domain: automation
              name: 'Theater - *'
        sort:
          method: name
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Weston
        filter:
          include:
            - domain: automation
              name: 'Weston - *'
        sort:
          method: name
