title: Solar
path: solar
icon: 'mdi:solar-power'
badges: []
cards:
  - title: Current House Stats
    type: 'custom:power-wheel-card'
    color_power_icons: true
    solar_icon: 'mdi:solar-power'
    grid_power_entity: sensor.solar_consumptionmeter_pvs5m644235c
    solar_power_entity: sensor.solar_raw_total_power
    power_decimals: 2
    grid_energy_entity: sensor.house_daily_net_energy
    home_energy_entity: sensor.solar_daily_house_usage_energy
    solar_energy_entity: sensor.solar_daily_energy
    energy_price: 0.11
    money_unit: $
    production_is_positive: false

  - title: Historical Energy Stats
    type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.house_daily_net_energy
        name: Daily Net Energy
      - entity: sensor.house_monthly_net_energy
        name: Monthly Net Energy
      - entity: sensor.solar_daily_energy
        name: Daily Solar Energy
      - entity: sensor.solar_monthly_energy
        name: Monthly Solar Energy

  - type: 'custom:mini-graph-card'
    extrema: true
    hour24: true
    hours_to_show: 72
    points_per_hour: 4
    upper_bound: 10
    entities:
      - sensor.solar_raw_total_power
      - sensor.solar_raw_house_usage

  - type: entities
    title: Panel Details
    show_header_toggle: false
    entities:
      - type: 'custom:auto-entities'
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: All
        filter:
          include:
            - entity_id: sensor.solar_inverter_*
        sort:
          method: state
          numeric: true
          reverse: true

      - type: custom:fold-entity-row
        head:
          type: section
          label: Graph
        entities:
          - type: 'custom:auto-entities'
            card:
              type: 'custom:mini-graph-card'
              extrema: true
              hour24: true
              hours_to_show: 24
              points_per_hour: 4
              upper_bound: .35
              show:
                name: false
                icon: false
                state: false
                legend: false
            filter:
              include:
                - entity_id: sensor.solar_inverter_*