title: Weather
path: weather
icon: 'mdi:weather-partly-cloudy'
badges: []
cards:
  - title: Weather
    type: 'custom:weather-card'
    entity: weather.dark_sky
    icons: "/local/community/weather-card/icons/"

  - type: picture-entity
    entity: camera.radar

  - type: weather-forecast
    entity: weather.daily_forcast
  - type: 'custom:weather-card-chart'
    title: Weather Daily
    weather: weather.daily_forcast

  - type: weather-forecast
    entity: weather.hourly_forcast
  - type: 'custom:weather-card-chart'
    title: Weather - Hourly
    weather: weather.hourly_forcast
    mode: hourly
