- platform: template
  sensors:
    bolt_charging:
      friendly_name: 'Bolt - Charging'
      value_template: '{{ state_attr("sensor.bolt_raw", "is_charging") }}'
      device_class: battery_charging
