- platform: template
  sensors:
    dark_outside:
      friendly_name: "Dark Outside"
      value_template: >-
        {{ 
          (states('sensor.home_power_production')|float < 750)
          or
          (state_attr('sun.sun', 'rising') and state_attr('sun.sun', 'elevation')|float < 1)
          or
          (not state_attr('sun.sun', 'rising') and state_attr('sun.sun', 'elevation')|float < 33)
        }}
