esphome:
  name: garage-thermostat

esp8266:
  board: esp01_1m

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret garage_thermostat_ip
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-thermo Fallback Hotspot"
    password: !secret wifi_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_pass

web_server:
  port: 80

time:
  - platform: sntp
    id: my_time

switch:
  - platform: gpio
    id: heater
    name: "Heater"
    pin: 
      number: GPIO0 # D3
      inverted: true

# These are default settings
i2c:
  sda: GPIO4 # D2
  scl: GPIO5 # D1
  scan: true

sensor:
  - platform: aht10
    temperature:
      id: garage_temp
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 15s

# https://esphome.io/components/climate/thermostat.html
climate:
  - platform: thermostat
    name: "Garage Thermostat"
    sensor: garage_temp
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    visual:
      min_temperature: 0
      max_temperature: 21
      temperature_step: 0.5