esphome:
  name: "sonoff-stair-lights"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret sonoff_stair_lights_ip
    gateway: !secret gateway
    subnet: !secret subnet

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

web_server:
  port: 80

time:
  - platform: sntp
    id: my_time

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Stair Lights Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Stair Lights Outlet Status"

sensor:
  - platform: wifi_signal
    name: "Stair Lights WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Stair Lights Current"
      accuracy_decimals: 1
    voltage:
      name: "Stair Lights Voltage"
      accuracy_decimals: 1
    power:
      id: power
      name: "Stair Lights Power"
      accuracy_decimals: 4
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kW
  - platform: total_daily_energy
    name: "Stair Lights Energy"
    power_id: power
switch:
  - platform: gpio
    name: "Stair Lights Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin: GPIO13