name: Home Assistant - CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home_assistant_stable:
    runs-on: ubuntu-latest
    
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Generate secrets.yaml
        run: |
          grep -r -h -o "\!secret [a-zA-Z\-\_][a-zA-Z0-9\-\_]*" . | sed -E 's/\!secret ([a-zA-Z0-9\-\_]*)/\1: X/g' | sort | uniq > secrets.yaml
          sed -E -i 's/(.*)_url: X/\1_url: https\/\/\:home\-assistant\.com/g' secrets.yaml
          sed -E -i 's/(.*)_(num|port): X/\1_\2: 0/g' secrets.yaml
          sed -E -i 's/(.*)_ip: X/\1_ip: 1.1.1.1/g' secrets.yaml
          cat secrets.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./ --script check_config --info all
