name: Home Assistant - CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home_assistant_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Generate secrets.yaml
        run: |
          grep -r -h -o "\!secret [a-zA-Z\-\_][a-zA-Z0-9\-\_]*" . | sed -E 's/\!secret ([a-zA-Z0-9\-\_]*)/\1: X/g' | sort | uniq > secrets.yaml
          sed -E -i 's/(.*)_url: X/\1_url: https\:\/\/home\-assistant\.com/g' secrets.yaml
          sed -E -i 's/(.*)_(num|port): X/\1_\2: 12/g' secrets.yaml
          sed -E -i 's/(.*)_ip: X/\1_ip: 1.1.1.1/g' secrets.yaml
          sed -E -i 's/zwave_network_key: X/zwave_network_key: 0x2e, 0xcc, 0xab, 0x1c, 0xa3, 0x7f, 0x0e, 0xb5, 0x70, 0x71, 0x2d, 0x98, 0x25, 0x43, 0xee, 0x0c/g' secrets.yaml
          cat secrets.yaml
      - name: Generate google-service-account.json
        run: |
          echo {\"private_key\":\"1\"\,\"client_email\":\"2\"} > ./config/google-service-account.json
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version
      - name: Home Assistant Config Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./config --script check_config --info all

  home_assistant_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Generate secrets.yaml
        run: |
          grep -r -h -o "\!secret [a-zA-Z\-\_][a-zA-Z0-9\-\_]*" . | sed -E 's/\!secret ([a-zA-Z0-9\-\_]*)/\1: X/g' | sort | uniq > secrets.yaml
          sed -E -i 's/(.*)_url: X/\1_url: https\:\/\/home\-assistant\.com/g' secrets.yaml
          sed -E -i 's/(.*)_(num|port): X/\1_\2: 12/g' secrets.yaml
          sed -E -i 's/(.*)_ip: X/\1_ip: 1.1.1.1/g' secrets.yaml
          sed -E -i 's/zwave_network_key: X/zwave_network_key: 0x2e, 0xcc, 0xab, 0x1c, 0xa3, 0x7f, 0x0e, 0xb5, 0x70, 0x71, 0x2d, 0x98, 0x25, 0x43, 0xee, 0x0c/g' secrets.yaml
          cat secrets.yaml
      - name: Generate google-service-account.json
        run: |
          echo {\"private_key\":\"1\"\,\"client_email\":\"2\"} > ./config/google-service-account.json
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --version
      - name: Home Assistant Config Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --config ./config --script check_config --info all

  home_assistant_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Generate secrets.yaml
        run: |
          grep -r -h -o "\!secret [a-zA-Z\-\_][a-zA-Z0-9\-\_]*" . | sed -E 's/\!secret ([a-zA-Z0-9\-\_]*)/\1: X/g' | sort | uniq > secrets.yaml
          sed -E -i 's/(.*)_url: X/\1_url: https\:\/\/home\-assistant\.com/g' secrets.yaml
          sed -E -i 's/(.*)_(num|port): X/\1_\2: 12/g' secrets.yaml
          sed -E -i 's/(.*)_ip: X/\1_ip: 1.1.1.1/g' secrets.yaml
          sed -E -i 's/zwave_network_key: X/zwave_network_key: 0x2e, 0xcc, 0xab, 0x1c, 0xa3, 0x7f, 0x0e, 0xb5, 0x70, 0x71, 0x2d, 0x98, 0x25, 0x43, 0xee, 0x0c/g' secrets.yaml
          cat secrets.yaml
      - name: Generate google-service-account.json
        run: |
          echo {\"private_key\":\"1\"\,\"client_email\":\"2\"} > ./config/google-service-account.json
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: python -m homeassistant --version
      - name: Home Assistant Config Check
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: python -m homeassistant --config ./config --script check_config --info all